### ISSUE TITLE
Close, solved

### ISSUE THREAD

**Issue by Amakna** [yanggis/ChinaTunnel#1]
Please close, Thanks!

**Comment by yanggis** [comment]
您好，感谢反馈！您 用ipservice.163.com/isFromMainland多检查几次，每次都不会返回为TRUE吗？另外除了小米视频，其他视频可以看吗？比如乐视视频或者优酷视频？

**Comment by yanggis** [comment]
chinatunnel默认是不需要配置任何服务器的，您只需update white list然后点右上角的那个switch就可以正常使用了。另外您可以告诉我一下您的IP的前两位，我登录服务器看看通讯是否正常。

**Comment by Amakna** [comment]
目前多檢查幾次會變成 true，測試了優酷視頻、樂視直播網球和高爾夫都可以看，就惟獨小米電視會員的部分會顯示區域不支持的錯誤，之前小米電視會員視頻從7/28開始到8/6都可以看的，也是用CT成功的。IP前兩位應該是123.110(因為有用小米路由器分享，小米小盒子裡看到的是192.168)，再麻煩您幫忙，非常謝謝!

**Comment by yanggis** [comment]
您好，您换回Chinatunnel 1.5试试看看可不可以播放呢？这样的话我可以知道是不是因为升级版本引起的？如果换回去1.5版本可以用，最新的1.5.1不能用，我就知道应该是软件的问题，如果换回1.5还不能用，应该就是whitelist问题。期盼您的测试回复！谢谢！

**Comment by Amakna** [comment]
剛反安裝 CT 1.5.1後，重新安裝 CT 1.5更新白名單後，小米電視付費會員就都可以看了!!!  持續觀察回報中，非常感謝您~

**Comment by yanggis** [comment]
嗯，感谢反馈！所以您现在用的是1.5版的吗？等我检查一下1.5.1是不是有什么题导致了1.5.1用不了。
