### ISSUE TITLE
2.1.1 -- 2.1.3 自从三天前均无法运行

### ISSUE THREAD

**Issue by NullFF00** [yanggis/ChinaTunnel#103]
报错截图如下, 坐标北美

![error](https://user-images.githubusercontent.com/40477859/41751279-589e7f1e-7575-11e8-8301-29f9f5fd929c.jpg)

难道说还要手动设置代理吗？

**Comment by yanggis** [comment]
你的是什么设备啊？

**Comment by NullFF00** [comment]
PC端的Android模拟器，夜神模拟器V6.0.1.1 https://www.yeshen.com/

**Comment by yanggis** [comment]
好吧，这个我测试一下，还真没有在PC端模拟器上测试过……

**Comment by yanggis** [comment]
我刚才装了这个模拟器看了，是你这个模拟器参数配置有问题。原因是本来你的PC端模拟器应该是x86版本，但是它的系统参数里面却把CPU写成了是armeabi-v7a,导致chinatunnel以为是arm的CPU，采用了arm的解锁方法，自然就启动不了。
解决办法，安装RE软件，编辑/system/build.prop文件，
找到这一行ro.product.cpu.abi2=armeabi-v7a
把armeabi-v7a改成x86，然后保存再重新启动，然后再检查/system/build.prop文件里是否修改成功了，如果修改成果再启动chinatunnel应该就可以了。

**Comment by NullFF00** [comment]
进去build.prop看了，发现cpu那一行默认就是x86。
![build](https://user-images.githubusercontent.com/40477859/41756703-bf9ad68c-7592-11e8-8444-50a1cc29ce29.jpg)

**Comment by NullFF00** [comment]
刚才看错了，把abi看成是abi2了。重启了一下还是不行
![build](https://user-images.githubusercontent.com/40477859/41756809-53b69964-7593-11e8-846a-9ac1c9d23d78.jpg)

**Comment by yanggis** [comment]
你修改没成功，用这个方法修改试试：
Mount system via recovery.
Open a cmd
cd into your tools folder
adb pull /system/build.prop
Edit it.
adb push build.prop /system/build.prop
adb reboot

**Comment by yanggis** [comment]
是这一行：ro.product.cpu.abi2=armeabi-v7a
不是ro.product.cpu.abi=x86这一行，系统检测你用的什么CPU是看ro.product.cpu.abi2参数。

**Comment by NullFF00** [comment]
谢谢回复。上面那个Recovery不太会操作修改。 还有一点好奇的是截止上周还一切正常的，这几天就提示代理运行不正常了，不清楚是怎么回事。

**Comment by yanggis** [comment]
这行ro.product.cpu.upgradeabi=armeabi也改成x86

**Comment by yanggis** [comment]
改完之后用Root Explorer.apk只读打开，看看显示的是否正确。

**Comment by NullFF00** [comment]
全部改成x86了，只读权限用的ES文件浏览器改的，还是不行

**Comment by yanggis** [comment]
我刚刚改了一下代码，你下载今天刚编译发布的版本试试。

**Comment by NullFF00** [comment]
下了刚刚发布的版本还是不行，提示代理运行不正常。我刚才一直在试着改build.prop，结果把模拟器搞崩了好几回。不敢再试了，能不能麻烦你测试一下啊。还有，我这样用了有好几个月了，最近才开始提示代理运行不正常。

**Comment by hkg520** [comment]
在手機或android盒子上用chinatunnel前必須做一次root機, 請問在PC端的Android模拟器上用chinatunnel是否需要root呢? 本人沒有用過PC的android模拟器也沒有聽過在模拟器可以root, 所以好奇一問.

**Comment by yanggis** [comment]
@NullFF00 你的问题我已经看了，就是你这个模拟器提供的CPU参数不正常导致的，明明它是x86的CPU，它提供的却是armeabi-v7a的CPU信息，导致chinatunnel对CPU信息判断错误。用RE改build.prop是没用的，重启加载到系统的参数仍然是armeabi-v7a。建议你用以前的版本的chinatunnel.

**Comment by yanggis** [comment]
或者你可以问问这个模拟器开发团队的人怎么修改那个参数。

**Comment by pongkunlo** [comment]
優酷視頻世界杯一直出现版權原因無法覌看

**Comment by yanggis** [comment]
@pongkunlo 优酷世界杯没有加入解锁链接。基本上都是转播的央视，CCTV5很多链接都可以看。

**Comment by pongkunlo** [comment]
Cctv5ㄧ樣版權原因無法觀看
