### ISSUE TITLE
安卓8不能用

### ISSUE THREAD

**Issue by a25722882** [yanggis/ChinaTunnel#104]
安卓8我有兩隻手機不能用小米5.小米6.後台都開了也root其他安卓7都可
Root是用magisk

**Comment by yanggis** [comment]
第一次运行弹出root授权对话框了吗？

**Comment by a25722882** [comment]
當然

**Comment by a25722882** [comment]
剛剛發現紅米note5安卓8.1也不行也就是真的安卓問題了！

**Comment by yanggis** [comment]
你微信联系我，帮你看看

**Comment by a25722882** [comment]
我沒看到你I'd,我的微信是a0970293480

X.K. YANG <notifications@github.com> 於 2018年6月23日 週六 下午11:16 寫道：

**Comment by a25722882** [comment]
我有傳我的維信號在信箱記得看～找不到您的微信

**Comment by a25722882** [comment]
記得哦～～

**Comment by yanggis** [comment]
搜不到你的微信号

**Comment by a25722882** [comment]
阿～剛沒開id在試一次
