### ISSUE TITLE
X96 mini电视盒子看蜜蜂视频很卡

### ISSUE THREAD

**Issue by JanusPro** [yanggis/ChinaTunnel#105]
我的电视盒子是x96 mini 2GB RAM/16GB ROM，安卓7.1，买回来已经root了，也正在使用最新版本的ChinaTunnel，以前看蜜蜂视频很顺的，如果卡的话转换成普通高清画质也是很顺，不过最近真的很卡，画质换普通高清都会卡一下播一下。

**Comment by yanggis** [comment]
蜜蜂视频是用的什么视频源啊？搜狐，腾讯，爱奇艺，还是其他的啊？

**Comment by JanusPro** [comment]
爱奇艺

**Comment by JanusPro** [comment]
还有补充一下，我使用TW和SG都面对一样的问题，但是用US的话选择普通高清画质就非常的顺了

**Comment by yanggis** [comment]
哦，不同的服务器速度会略有不同，看你在什么国家

**Comment by JanusPro** [comment]
我在马来西亚，SG的不是比较适合吗？

**Comment by yanggis** [comment]
是比较合适，你用SG的服务器会很卡吗？

**Comment by yanggis** [comment]
你为什么不安装爱奇艺的官方APP看爱奇艺呢？银河奇异果是他们的官方APP啊

**Comment by JanusPro** [comment]
SG服务器昨天用就真的很卡，今天就比较正常比较顺了。
因为家里有小朋友要方便他们找片不用一直换app找所以才用蜜蜂视频。如果再找不到的话才换电视猫。

**Comment by jayoscar** [comment]
我用小米盒子增强版 这两天云视听极光 和小米自己的 newtv 一样卡, 几乎只能用最低那个清晰度来链接美国服务器了， 基本上台湾和新加坡的服务器根本不能用啊。 如果自己假设一个私人的服务器， 希望可以技术指导下。

**Comment by jayoscar** [comment]
我觉得马来西亚链接中国的视频都是卡卡的。

**Comment by yanggis** [comment]
@jayoscar 您在哪个国家？

**Comment by yanggis** [comment]
一般应该不卡才对，提供视频APP名字和看得节目的名字，我测试一下

**Comment by JanusPro** [comment]
早上本来没问题的，从下午开始卡了，换了银河奇异果也是一样播一下卡一下，画质流畅都这样，网速加载有显示700kb/s - 1.5mb/s，SG服务器。中国梦想秀第七季 第四期
是多人在用的关系吗？

**Comment by yanggis** [comment]
@jayoscar 麻烦再测试一下爱奇艺的视频源，看看速度有没有提高？

**Comment by jayoscar** [comment]
好的，晚上到家就测试。

**Comment by JanusPro** [comment]
不懂 @jayoscar  的问题有没有解决，现在看爱奇艺的速度提高了，也比较稳了
