### ISSUE TITLE
人在德国速度很卡

### ISSUE THREAD

**Issue by lixing345** [yanggis/ChinaTunnel#111]
昨天换了最新版本
机器是小米盒子增强版 视频速度只有30KB左右根本没法看
看小米自带
网速400MB光纤
估计你们服务器问题请尽快处理
不管是台湾服务器还是 新加坡或者是美国服务器 都特别慢

**Comment by lixing345** [comment]
我希望你们能尽快搞出一个欧洲的服务器谢谢

**Comment by yanggis** [comment]
这个暂时没有计划搞欧洲的服务器，因为chinatunnel是一个免费APP，资金非常有限。您的问题要说明用的是小米盒子自带的视频，还是安装的别的APP，是什么APP？

**Comment by lixing345** [comment]
您好，
谢谢您的回复

小米自带视屏
其他的也是 白天特别卡
半夜里正常
祝好

**Comment by lixing345** [comment]
可是之前不卡啊
最近几天才卡的
之前都能达到2000kb/s
祝好

Am 02.07.2018 um 08:26 schrieb X.K. YANG <notifications@github.com>:

**Comment by yanggis** [comment]
是小米自带的视频源吗？

**Comment by lixing345** [comment]
能不能以后这样 开放一个付费服务器
要不然人多了体验太差 最后没人用了
还有个问题
在软件里有个自己服务器设置 这个怎么用
我觉得如果让大家付费 这个软件才能做的长远
谢谢
祝好

Von meinem iPhone gesendet

**Comment by dieter313** [comment]
也在德国, 也是小米盒子3增强版, 这几天的确是特别卡, 无论哪个app都一样. 切回DNS倒是还能看

**Comment by yanggis** [comment]
如果是个别app卡，可能是chinatunnel的原因，如果所有APP都卡，那很有可能是小米盒子搞了升级引起的盒子本身的系统问题。你可以想想这几天之前小米盒子是否自动升级过。

**Comment by yanggis** [comment]
人数是比较多，并不是每个视频源人都多啊，不会所有视频源都卡

**Comment by lixing345** [comment]
我的小米盒子升级过
是的
Am 03.07.2018 um 02:19 schrieb X.K. YANG <notifications@github.com>:

**Comment by chinawinner** [comment]
V99 4g 32g, 这两天升到2.13特别卡。没法看

**Comment by yanggis** [comment]
@chinawinner 谢谢反馈，主要是什么视频比较卡？

**Comment by yanggis** [comment]
@lixing345 @chinawinner 今天换了新的服务器，麻烦再测试一下速度。

**Comment by dieter313** [comment]
现在又和原来一样流畅了,非常感谢！！！
