### ISSUE TITLE
云视听小电视（bilibili 小米盒子tv版）

### ISSUE THREAD

**Issue by yuan7521** [yanggis/ChinaTunnel#113]
云视听小电视这个软件看不了，显示地域问题。能不能帮忙解决一下？另一个b站盒子版软件能看，但是卡顿非常严重。本人在美国使用，台湾 美国 和新加坡服务器都试过了，都是不行。麻烦你了，谢谢

**Comment by yuan7521** [comment]
我是在沙发管家里下的 云视听小电视（下载前叫哔哩哔哩tv版，下载出来就是 云视听小电视了 ），是和b站合作的。http://m.shafa.com/apk/yunshitingxiaodianshi.html

**Comment by yanggis** [comment]
好的，我再看看吧

**Comment by yanggis** [comment]
今天换了新的服务器，麻烦再试试看速度有没有改善？

**Comment by yuan7521** [comment]
试了一下，哔哩哔哩盒子版可以流畅观看了。谢谢你的帮助。

**Comment by yutongp** [comment]
我也遇到了同样的问题。2.1.4版本 银河奇异果(爱奇艺)可以看，但 云视听小电视(bilibili)却不行。三地的服务器都试过了，白名单也刷新过了，没有帮助。不能看。

**Comment by yanggis** [comment]
@yutongp 不应该啊，我前两天刚试过还可以播放，你不能播放的时候提示什么问题？是提示版权问题吗？

**Comment by yutongp** [comment]
@yanggis 我这边显示暂不能播放此视频
我的盒子是小米3增强版 云视听小电视 是最新版本 chinatunnel是2.1.4
云视听小电视的三种解码方式我也都试过了…

**Comment by yanggis** [comment]
@yutongp 这说明是可以解锁的，否则会跳出版权信息提示。你应该安装chinatunnel 2.2.0. 另外你在哪个国家？

**Comment by yutongp** [comment]
我坐标北美

**Comment by yanggis** [comment]
@yuan7521 我估计是你因为你离亚洲的服务器比较远，这个看起来像是解锁生效，但是你那边和解锁服务器通讯有点问题。你播放腾讯云视听的视频正常吗？

**Comment by hfknight** [comment]
我的云视听小电视也有这个问题,普通的视频可以播放但是无法播放受版权保护的视频;旧的哔哩哔哩还能正常播放所有的视频. 坐标北美.
