### ISSUE TITLE
20180810清晨02:00,三個服務器都無法使用

### ISSUE THREAD

**Issue by jeff0604tw** [yanggis/ChinaTunnel#120]
請問是否伺服器維修呢?
開啟chinatunnel後出現Can't get proxy ip ...set DNS to 8.8.8.8 ....

**Comment by yanggis** [comment]
godday负责给chinatunnel做域名服务器的服务商down机了，现在还没有修好

**Comment by sorrych** [comment]
原来如此，服务商一般多久可以处理好呢

**Comment by yanggis** [comment]
现在应该可以了
