### ISSUE TITLE
以后chinatunnel要收费了吗

### ISSUE THREAD

**Issue by sinochinois** [yanggis/ChinaTunnel#121]
看到新版本，有收费选项，请问以后要收费了吗？

**Comment by yanggis** [comment]
root版本会一直坚持免费策略；
VPN版本是新开发的，会收费有偿提供。

**Comment by yanggis** [comment]
https://github.com/yanggis/ChinaTunnel?files=1
这里可以下载，名字是chinatunnelVPN-1.1.0版本

**Comment by rockyliang** [comment]
昨晚测试了Chinatunnel的VPN版。不过一启动就闪退。使用的是小米3增强版最新系统。

**Comment by yanggis** [comment]
这个是因为小米盒子3增强版没有google play service模块。

**Comment by yanggis** [comment]
嗯，这个再调整一下。

**Comment by hurstvillechineseboy** [comment]
China Tunnel 不行了么， 我今天从国内回来，看电视时用“云电视猫”，看港剧，以前都可以的，现在就不行了，现象跟没有装China Tunnel前一样，不知道是“云电视猫”的问题还是CT的问题

**Comment by yanggis** [comment]
是因为电视猫刚升级了，等我这两天修复一下这个问题。

**Comment by hurstvillechineseboy** [comment]
好的，等您的消息

**Comment by yanggis** [comment]
https://software-download.microsoft.com/pr/Win10_1803_China_GGK_Chinese(Simplified)_x64.iso?t=045e5668-afa7-4ed7-bd09-e5004bcb32ce&e=1535951206&h=29f9199d1cbb9287c94a6a5dfaf1ee41

**Comment by hurstvillechineseboy** [comment]
请问有消息么，谢谢

**Comment by tunderspeed** [comment]
Hi, 请问root版本还能继续使用吗？

**Comment by yanggis** [comment]
现在不能使用了

**Comment by tunderspeed** [comment]
好的。谢谢。那请问普通电视盒子需要用哪个版本的china tunnel vpn?

**Comment by yanggis** [comment]
@tunderspeed 2.0.1版本的，随便安装一个都可以的。
