### ISSUE TITLE
爱奇艺无法观看

### ISSUE THREAD

**Issue by edient** [yanggis/ChinaTunnel#126]
最近爱奇艺只要启动chinatunnel就会一直显示全力加载中。如果关了chinatunnel马上就能看到所有内容。不知道如何解决

**Comment by yanggis** [comment]
您好，谢谢反馈，您用的哪个服务器？

**Comment by carlosvivi2018** [comment]
您好，我也遇到了同样问题。昨天开始的，昨晚重新换服务器试几次有时还可以显示出内容。今早就不行了，三个服务器都试过，已更新白名单。

**Comment by yanggis** [comment]
现在应该好了吧？是我们的DNS服务商出了问题，已经联系他们解决了。

**Comment by carlosvivi2018** [comment]
谢谢大神，已经可以看了！
