### ISSUE TITLE
2.1.4无法启动

### ISSUE THREAD

**Issue by NullFF00** [yanggis/ChinaTunnel#127]
目前使用的是夜神模拟器6.2.0.0版本，之前的解答中告知使用2.0.2版本。直到现在，2.0.2好像不是那么好用了。 尝试升级2.1.4版本，报错提示TCP被占用。 升级夜神模拟器至最新版6.2.3.0还是一样。 还请作者解答一下

附：报错信息截图
![erroe_2 1 4](https://user-images.githubusercontent.com/40477859/44304924-ab6a8a80-a31f-11e8-8166-8c624a6240ef.JPG)

**Comment by yanggis** [comment]
这个是因为夜神模拟器提供的内核参数不对，你这个在电脑上运行应该是x86的内核，chinatunnel检测你的模拟器的时候得到的内核却是arm的内核，于是就按照arm的内核运行，造成启动失败。
