### ISSUE TITLE
出現Can't get proxy ip ...set DNS to 8.8.8.8 ....

### ISSUE THREAD

**Issue by jeff0604tw** [yanggis/ChinaTunnel#131]
請問是否伺服器維修呢?經常出現這訊息
開啟chinatunnel後出現Can't get proxy ip ...set DNS to 8.8.8.8 ....

**Comment by yanggis** [comment]
是DNS的问题，你把你的盒子的DNS设置为8.8.8.8应该问题就解决了。

**Comment by jeff0604tw** [comment]
最近常常發生...以前不會這樣啊...怪了!!

**Comment by yanggis** [comment]
是DNS的问题，你把你的盒子的DNS设置为8.8.8.8应该问题就解决了.
