### ISSUE TITLE
請問現在還可以用阿里雲架設自己伺服器？

### ISSUE THREAD

**Issue by limnuts** [yanggis/ChinaTunnel#133]
https://m.aliyun.com/doc/document_detail/41342.html

有時chinatunnel 不太穩定 想自己架設一個再用chinatunnel連線 有什麼雲公司比較好？

**Comment by yanggis** [comment]
你用了VPS会发现你的VPS发生故障的概率比chinatunnel服务器发生故障的概率更高，没太大必要自己单独花钱架设服务器。

**Comment by limnuts** [comment]
現在繁忙時間晚上8-11左右都不太穩定
有什麼改善方法

**Comment by limnuts** [comment]
好的謝謝 我試一試 
你們有讚助計劃？

**Comment by yanggis** [comment]
@limnuts 有赞助计划，欢迎支持我们。您可以用赞助直接购买我们的VPN服务(http://pay.yanggis.com)，VPN可以提供更多优质的服务器，解锁服务器选择新加坡或者洛杉矶的，速度应该会有保证。试用ChinatunnelVPN可以在google play里下载。

**Comment by limnuts** [comment]
好的 
另外期待你們出ios版本  ipad也可以用

**Comment by yanggis** [comment]
@limnuts 这个暂时没计划，sorry.

**Comment by hkg520** [comment]
請問老師的vpn服務會比原本chinatunnel更快嗎?

**Comment by yanggis** [comment]
理论上来讲会要快一点，因为VPN线路会比较多，你可以测试每一个线路，看看哪个线路对你那边来说解锁速度最快，这个你可以测试一下。非VPN线路是我们根据普通情况测试的结果，对于特定网路不一定是最秀的。

**Comment by limnuts** [comment]
用了vpn現在比較好 謝謝
