### ISSUE TITLE
腾讯视频TV版，今天突然不能看了

### ISSUE THREAD

**Issue by Fancy78** [yanggis/ChinaTunnel#134]
如题，今天（8月25号）打开显示后台服务器繁忙（2031,501），后台工程师正在修复，请稍后设置

关闭chinatunnel后可看，除了版权提示...

昨天还是好的

**Comment by yanggis** [comment]
麻烦再看看现在可以了没有？今天白天进行了线路升级改造，现在已经升级完了，线路已经恢复正常了。

**Comment by Fancy78** [comment]
好了，谢谢

**Comment by hanfeng1982** [comment]
小米盒子3增强版，优酷看不了。和上面腾讯的一样的问题。

**Comment by hanfeng1982** [comment]
开启chinatunnel后，视频一直转圈。关闭后可以正常链接，一部分无版权限制的就可以看了。

**Comment by yanggis** [comment]
@hanfeng1982 换新加坡的服务器试试。

**Comment by hanfeng1982** [comment]
亲，新加坡，北美，台湾全部试过了。盒子也重启过了。都不行呀。

**Comment by yanggis** [comment]
@hanfeng1982 您好，我看了，服务器是正常的啊，您在哪个国家？

**Comment by hanfeng1982** [comment]
亲，日本东京哈。以前一直用旧版本没有问题，最近出问题了，换了最新版还是不行哈。用的是小米盒子增强版

**Comment by yanggis** [comment]
@hanfeng1982 你要说关键啊，出的是什么问题啊？

**Comment by hanfeng1982** [comment]
位置:日本东京
设备:小米盒子增强版
问题:打开chinatunnel后，所有视频一直转圈加载中状态。关闭chinatunnel后，不限定位置的视频可以正常播放

**Comment by yanggis** [comment]
你用的什么宽带，如果和手机不是一个宽带运营商，可以把手机开WIFI热点，让电视盒子连你的手机，然后试试通过手机WIFI热点可以连不？
