### ISSUE TITLE
电视猫显示版权限制

### ISSUE THREAD

**Issue by rainyg** [yanggis/ChinaTunnel#137]
小米盒子3 ChinaTunnel 2.1.5北美服务器今天电视猫显示版权限制无法播放提示。ChinaTunnel显示启动成功并更新了白名单

**Comment by rainyg** [comment]
目前版本应该是最新的 3.2.5_32501

**Comment by tcm2008** [comment]
我的也是這個問題 之前是1.9.1的版本 優酷看TVB又沒有問題

**Comment by jeff0604tw** [comment]
電視貓部分影片會讓Chinatunnel停止回應! 然後Chinatunnel就自動關閉!! 例如說: 天命 1 跟 2 是沒有VIP,但是會造成Chinatunnel沒回應!

**Comment by tcm2008** [comment]
是的只是電視貓TVB 會出現地區限制
優酷的TVB沒問題 騰訊會很慢很久都打不開視頻

**Comment by yanggis** [comment]
@tcm2008 我看了电视猫，没有找到你说的TVB港剧，没有办法测试。

**Comment by rainyg** [comment]
可以搜索创世纪 粤语版。今天下午试过还是没办法看

**Comment by yanggis** [comment]
@rainyg 看了您说的创世纪，1999年的老电视剧，这些老电视剧都是电脑猫单独采用p2p技术外连的别的版权商，目前暂时没有太好的办法解决这个问题。chinatunnelVPN目前也没有加入对p2p链接的支持。

**Comment by yanggis** [comment]
你能做最好的办法可能就是按照旧版的电视猫，用旧版的电视猫观看。

**Comment by tcm2008** [comment]
我的電視貓沒更新過 是突然不能看了 你可以搜索天命 特技人

**Comment by tcm2008** [comment]
之前都能看 我看到第五集了 前幾天想繼續看的時候就不能看了
