### ISSUE TITLE
China Tunnel 好像已经不能翻墙进大陆了，看不到电视猫，泰捷和电视家

### ISSUE THREAD

**Issue by hurstvillechineseboy** [yanggis/ChinaTunnel#138]
之前可以的，现在不行了，装了最新版本2.14 也不行，出现的情况跟不能之前没有装China Tunnel时一样，很急，老人家快回来了，没有港剧看，是不是真的要付款买VPN版本才可以啊。

**Comment by yanggis** [comment]
老的港剧电视剧都是电脑猫单独采用p2p技术外连的别的版权商，目前暂时没有太好的办法解决这个问题。chinatunnelVPN目前也没有加入对p2p链接的支持。不要因为这个购买vpn版本。
