### ISSUE TITLE
2.1.4無法在華碩變形平板TF303CL使用

### ISSUE THREAD

**Issue by caf0696** [yanggis/ChinaTunnel#141]
使用時會出現「啟動失敗, TCP PORT USED BY ANOTHER APP?」
OS是 ANDROID 4.4,有ROOT
目前使用2.0.2,運作正常
請問是不支持intel cpu的關係嗎？

**Comment by caf0696** [comment]
您好，這款平板用的是 intel atom z3745,所以應該是x86架構的

**Comment by yanggis** [comment]
刷最新版2.2.0版本试试。

**Comment by caf0696** [comment]
您好, 裝上最新版的 2.2.0 以後確認可以在TF303CL 上執行, 謝謝!
