### ISSUE TITLE
shield  TV可以用吗

### ISSUE THREAD

**Issue by henryxia0312** [yanggis/ChinaTunnel#142]
能否有指导安装图示，在shield TV上不知怎么登陆怎么操作和设置

**Comment by henryxia0312** [comment]
能否有指导安装图示，在shield TV上不知怎么登陆怎么操作和设置
我指的是VPN版本

**Comment by yanggis** [comment]
启动chinatunnelVPN以后会看到一行字“请在右侧菜单申请账号试用”，点那行字右侧黑色的第二个小图标（小笔形状）。点了之后就可以看到配置服务器，端口和密码了。你把服务器分配给你的置服务器地址(比如洛杉矶的是la.yanggis.com)，端口和密码填进去，然后点右上角的对号按钮保存。然后点右下角黄色启动按钮就可以启动VPN服务了。

不同的服务器针对你所在的区域网速不一样。你可以同时配置多个服务器，一个一个试试看看哪个服务器在你那边访问速度最快，就固定用这个服务器就好了。
要添加新服务器配置在界面的右上角有个加个按钮，点它既可添加新服务器配置。

有问题可以再在这询问。

**Comment by yanggis** [comment]
![chinatunnelvpn2](https://user-images.githubusercontent.com/6284797/45633839-747cc580-bad3-11e8-9882-80f7a9b63ef1.jpg)


![chinatunnelvpn1](https://user-images.githubusercontent.com/6284797/45633846-79da1000-bad3-11e8-93e3-92d3eb0cec4a.jpg)
