### ISSUE TITLE
应版权方要求暂不提供播放服务(50101,1300080)

### ISSUE THREAD

**Issue by MoochinLiu** [yanggis/ChinaTunnel#147]
我已购买了会员，想观看《我就是演员》。购买之后，再次点击节目，出现“应版权方要求暂不提供播放服务(50101,1300080)”的错误提示，不知道有什么方法解决？多谢啦！

**Comment by sololau00** [comment]
打开chinatunnel 更新whitelist（白名单）选择离你近的地点。比如你在中国那么就选择台湾的服务器。我的可以观看。如果不行换个chinatunnel 试下
