### ISSUE TITLE
Smart Youtube App，Youtube App 或 用Browser 開 Youtube 都會在開啟了 ChinaTunnel 的時候會出現頁面停止無法播放但有聲音，就算後來關閉了連接，清了內存或重啟盒子，都還是無法播放。

### ISSUE THREAD

**Issue by chocolatetea** [yanggis/ChinaTunnel#148]
有时候重启盒子好幾次，能播10分钟左右，然后Youtube视频就会再次出现卡顿，有声音没画面或停止了的画面。

用的是MXIII的安卓盒子，網絡測速顯示可以看超清的視頻，觀看中國的視頻沒有任何問題，超好的，但看這邊北美的視頻就變成看不了。

所以不清楚是不是翻牆到中國的話，就不能兼容看這邊北美的視頻了。不論用Smart Youtube App，Youtube App 或 Browser 的 Youtube 都無法播放。刷新好多次都不行，就算選其他視頻還是看不了。请问大家有同類的問題嗎？

**Comment by yanggis** [comment]
@chocolatetea 你是用的最新版的ChinatunnelVPN版本吗？

**Comment by chocolatetea** [comment]
@yanggis 用的是需要Root的這款(https://play.google.com/store/apps/details?id=com.yanggis.chinatunnel)，然後Root是用Supersu。

**Comment by yanggis** [comment]
@chocolatetea 这个最大的可能是你的盒子ROM有bug，root版本进行了严格的数据包过滤，除了过了的特殊数据包之外，别的数据包都是原路发送的，和chinatunnel没有任何关系。如果出现你这种情况最大可能就是你的ROM有问题，自身对数据包过滤有bug.

**Comment by chocolatetea** [comment]
@yanggis 啊，原來是盒子的問題，我想請問下盒子的ROM的問題會不會很難解決，因為對這些不是很懂，要是裝了的ChinaTunnel換成剛提到的新的那個ChinaTunnelVPN，不經過Root ，請問這樣能解決盒子的bug嗎？

**Comment by yanggis** [comment]
VPN版本是免费试用的，你可以申请个试用账号用一个星期看看速度能不能满足你的要求，满足的话你再考虑买。

**Comment by chocolatetea** [comment]
@yanggis 因為盒子買的時候也自帶Youtube App, 然後在Browser上也看過youtube視頻，然後用了好長一段時間也沒什麼問題，Smart Youtube App 也是最近才安裝的，然後沒翻牆的時候，也能正常播放，所以不太清楚發生什麼。

**Comment by chocolatetea** [comment]
@yanggis 嗯嗯，有空試下

**Comment by iam3ddy** [comment]
@yanggis 那個ChinaTunnelVPN付费才有新加坡节点吗？
免费试用能不能加新加坡试试？

**Comment by yanggis** [comment]
@iam3ddy 新加坡节点是在付费区才有，您可以先用一下台湾2，或者洛杉矶的速度怎么样。

**Comment by chocolatetea** [comment]
@yanggis 好像還是不行，Smart Youtube App，Youtube App，Browser的Youtube都還是無法播放，應該是盒子問題TT。。

**Comment by chocolatetea** [comment]
应该是盒子ROM的问题。
