### ISSUE TITLE
在小米盒子上不能工作

### ISSUE THREAD

**Issue by l-z** [yanggis/ChinaTunnel#15]
您好， 今天我的小米盒子3增强版 1.5.2 和小米盒子迷你 1.5.4上开了china tunnel 1.7.6之后 所有的视频都不能看了。至少两周前还是可以的。 是服务器的问题吗

**Comment by l-z** [comment]
播放错误代码是600，201

**Comment by yanggis** [comment]
是小米盒子自带的视频APP吗？VST可以看不？企鹅云视听可以看吗？

**Comment by l-z** [comment]
对， 小米盒子自带的视频都不能用了
云视听能够正常工作（开启ChinaTunnel部分视频可以看，开启后都可以看）

**Comment by l-z** [comment]
自带app里的腾讯来源的视频可以工作，但是爱奇艺来源的视频都不工作里
单独下载的爱奇艺app(银河 奇异果) 可以正常工作

**Comment by l-z** [comment]
好像和unblock youku 的问题一样
https://bbs.uku.im/t/vip/480/14
https://bbs.uku.im/t/vip-app-vip/483/2

**Comment by yanggis** [comment]
这个主要是我没有小米盒子，没法测试应该拦截哪个link，所以才出现这样的问题。以前有人帮我抓包了之后我把link加进去了，应该是可以了。你是不是最近更新小米盒子的APP或者盒子固件了？

**Comment by l-z** [comment]
最近没有更新， 这个版本用好久了。
有抓包的教程吗。我看看能不能帮你

**Comment by yanggis** [comment]
在你的小米盒子上安装这个app
https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture
然后运行起来，
然后打开小米盒子的app，选一个视频观看，知道跳出错误。关闭小米盒子的app，然后打开packetcapture，看看抓到的包，一个一个打开看，看看哪个包的内容里显示有你的IP地址或者你所在位置信息，把这个包的link发给我就可以了。

**Comment by l-z** [comment]
刚才试验一下又好了，
可能是下午抽风了。。

**Comment by bigboybig** [comment]
小米小盒子不能安裝china tunnel vpn apk
