### ISSUE TITLE
VPN版1.3withXiaomi3

### ISSUE THREAD

**Issue by gggbb123** [yanggis/ChinaTunnel#154]
安装了VPN1.3.0版，从你网站也申请了账户，也可以connect，但是测试的时候好像就不行了。 Disconnect的时候会有“Fail to detect internet connection. Unable to resolve host "www.google.com". No address associated with hostname"。  有什么建议吗？  是不是需要安装Google框架呢？

Chinatunnel2.2.3 的运作完全没问题！

**Comment by yanggis** [comment]
1.3.0版本测试有问题，但是不影响解锁；这问题在1.4.0版本已经修正了这个问题。

**Comment by gggbb123** [comment]
之前装过1.4.0但是用不了！是不是如果有Google框架就可以用吗？

**Comment by yanggis** [comment]
你的什么设备呢？

**Comment by gggbb123** [comment]
> 1.3.0版本测试有问题，但是不影响解锁；这问题在1.4.0版本已经修正了这个问题。

在1.3版里，虽然可以connect但是没有网路！  我进了你的pay.yinggis.com查看我户口，一点流量都没用到！ 我用的是小米盒3，有root access。

**Comment by gggbb123** [comment]
服务器端口：29420

我密码应该没错。  为确保没错，你可以把密码更新在发到我私人邮件吗？  应为我都搞不清"I" 和 “l”.  麻烦你帮帮忙！

> 你的vpn账号是什么？我查看一下。不要把chinatunnel的VPN版本和root版本一起安装，会造成冲突。

我没有删掉root版，会去试一试 。

**Comment by yanggis** [comment]
密码是随机生成的，你肯定是把密码搞错了，密码第三个字母是L的小写.

**Comment by gggbb123** [comment]
我删除了root版和修改了密码。 现在connect也不行了，显示一个“unable to connect to remote
server...sendfd  failed”.  试了hongkong.yanggis.com 和 tw2 都不行！

**Comment by yanggis** [comment]
在这个帖子第二楼我已经说了，
1.3.0版本测试有问题，但是不影响解锁；这问题在1.4.0版本已经修正了这个问题。

**Comment by gggbb123** [comment]
不光是测试不行，是连网路都接不上！

小米三盒要做什么修改才能装1.4.0版呢？

**Comment by yanggis** [comment]
@gggbb123 怎么可能会连不上？我这服务器上都能看到你的账号有流量，怎么会连不上网？

**Comment by gggbb123** [comment]
现在可以连接上了！可是怎么觉得网路比root版还要慢？ 尤其是在看奇艺的时候！

**Comment by yanggis** [comment]
你应该多尝试几个服务器，选速度最快的，而不是随便找一个你所在位置的服务器就认为是最快的，但是大多数情况下你所在位置的服务器不是速度最快的。
