### ISSUE TITLE
銀河奇異果(愛奇藝TV版)無法通過地區限制

### ISSUE THREAD

**Issue by fish7yu** [yanggis/ChinaTunnel#159]
銀河奇異果(愛奇藝TV版)無法通過地區限制，前2天還能用，昨天開始就被限制了。

**Comment by yanggis** [comment]
是因为你刚刚升级银河奇异果了吧？

**Comment by fish7yu** [comment]
最近並沒有升級奇異果，也試過重新安裝早期一點的奇異果，也是沒幫助，似乎奇異果在後台有做了修改。

愛奇藝手機版也是需要用比較舊的版本才可以克服區域的限制。

**Comment by yanggis** [comment]
谢谢反馈，我在检查是什么问题。

**Comment by fish7yu** [comment]
謝謝您!

現在看到的問題主要是影片與節目的頁面出不來，或是花了很久出來的頁面，很多以前有的內容都不見了。  不過在頁面上有出現的影片，播放是沒有問題的。

似乎奇異果在頁面出現的階段，就會有在管制區域，而用ChinaTunnel並無法讓奇藝果認為網路是在大陸。

**Comment by yanggis** [comment]
@fish7yu 现在应该解决了，麻烦测试有问题再反馈。

**Comment by fish7yu** [comment]
剛才試了一下，問題似乎是解決了，謝謝您!
