### ISSUE TITLE
开启后没效果

### ISSUE THREAD

**Issue by Menchen** [yanggis/ChinaTunnel#16]
没报错，用bilibili还是有版权限制（play商店的 4.32.0），用了两台手机测试了。。分别是 JB 的用 Supersu 和 S7E N 用 magisk su。。
![screenshot_20170228-154549](https://cloud.githubusercontent.com/assets/6707265/23409915/a840b8d2-fdcd-11e6-89af-a3a1b6567095.png)

**Comment by yanggis** [comment]
在手机上打开这个链接，看看是true 还是 false
http://ipservice.163.com/isFromMainland

**Comment by yanggis** [comment]
你点右上角那个开关，开启解锁服务了吗？

**Comment by Menchen** [comment]
开了，显示运行成功，然后 是 false, 不过如果用 unlock your 的 PAC  是 true ,( 不过好像 bilibili
 不走代理。。)

2017年2月28日 15:55，"X.K. YANG" <notifications@github.com>写道：

**Comment by Menchen** [comment]
截图上面也能看到开启了。。。

**Comment by yanggis** [comment]
保持chinatunnel解锁服务运行，
安装这个app
https://play.google.com/store/apps/details?id=jackpal.androidterm
然后运行起来，在命令窗口输入以下命令，
cat /etc/hosts
看看显示什么内容？

**Comment by Menchen** [comment]
![screenshot_20170228-160359](https://cloud.githubusercontent.com/assets/6707265/23410442/8e1fdf4e-fdcf-11e6-8787-e954a53d4fd2.png)
RE 开的。
![screenshot_20170228-160531](https://cloud.githubusercontent.com/assets/6707265/23410506/c28cac6c-fdcf-11e6-9d42-b6d07dce4039.png)
bilibili的

**Comment by yanggis** [comment]
嗯，这个配置没问题。
你用的是chinatunnel新加坡的服务器，还是北美的服务器？

**Comment by yanggis** [comment]
在刚才我给你说的那个app
https://play.google.com/store/apps/details?id=jackpal.androidterm
然后运行起来，在命令窗口输入以下命令，

iptables -t nat -L -n -v | grep 47.90.50

看看什么结果，grep前面那个是竖杠。

**Comment by Menchen** [comment]
2017年2月28日 16:14，"X.K. YANG" <notifications@github.com>写道：

**Comment by yanggis** [comment]
刚才看了，你说的这个play商店里的4.32版B站客户端估计已经作废了，现在必须安装B站最新的4.35.1客户端才可以用，以前版本都被B站官方废除了。你可以这里下载最新版：

http://coolapk.com/apk/tv.danmaku.bili

**Comment by Menchen** [comment]
http://imgur.com/FmhGJYZ
Iptables 的截图，github手机网页版的不能上传图片。。。现在去试试 酷安的Apk

**Comment by yanggis** [comment]
嗯，看到了，你这个配置也没问题，最大的可能就是你B站版本太老了。另外，你在番剧区换个番剧试试看看可以不？

**Comment by Menchen** [comment]
随便又点了2个还是一样。。。已经更新了

**Comment by yanggis** [comment]
http://ip.cn
看看你的IP是多少。你用的chinatunnel哪个服务器？新加坡的还是北美的？

**Comment by Menchen** [comment]
Ip 没改，2个服务器都试过了
您现在的 IP：66.249.93.27

所在地理位置：荷兰 Google

GeoIP: Europe

内部 IP: 62.174.55.148

来自：西班牙

GeoIP: Spain

**Comment by yanggis** [comment]
你选择用新加坡的服务器，再试一下。
