### ISSUE TITLE
优酷Tv 版（酷喵）

### ISSUE THREAD

**Issue by sololau00** [yanggis/ChinaTunnel#160]
其他视频都可以点播，只是港剧（兄弟）显示 暂无信息。他是找不到资源。可是我手机的优酷可以播放。
云视听小电视（bilibili 小米盒子tv版）
国漫可以看可是日漫看不到

**Comment by yanggis** [comment]
谢谢反馈，我检查一下

**Comment by sololau00** [comment]
好的

**Comment by sololau00** [comment]
为什么27集可以看然后最新的一集显示视频已屏蔽。

**Comment by sololau00** [comment]
酷喵看不到港剧罢了。
bilibili可以看了

**Comment by sololau00** [comment]
查到了吗？
