### ISSUE TITLE
BilibiliTv客户端

### ISSUE THREAD

**Issue by sololau00** [yanggis/ChinaTunnel#161]
我启动Chinatunnel打开Bilibili客户端他是无法加载连网。

**Comment by sololau00** [comment]
![image](https://user-images.githubusercontent.com/30999965/50384442-a23f5f00-06ff-11e9-8de2-2af9a5ce9e44.jpg)
![image](https://user-images.githubusercontent.com/30999965/50384453-b6835c00-06ff-11e9-9a25-c3e537ef60db.jpg)
如果没启动chinatunnel番剧无法观看，显现未开播，国漫可以观看。
我试了3个服务器一样问题
![image](https://user-images.githubusercontent.com/30999965/50384486-28f43c00-0700-11e9-9a54-893945bf085b.jpg)

**Comment by yanggis** [comment]
@sololau00 看看别的视频APP可以联网吗？比如腾讯视频，爱奇艺银河奇异果之类的。

**Comment by sololau00** [comment]
其他可以观看。除了bilibili ，另外你的chinatunnel开始出现这个问题，
一下子就失效了比如下一集就提示错误（地区限制）出去在点播就可以观看或者打开bilbili可以观看然后，几分钟后失效了。
