### ISSUE TITLE
关于vpn充值会员的问题

### ISSUE THREAD

**Issue by York868** [yanggis/ChinaTunnel#165]
请问充值会员除了流量有限制外 带宽是否能有保证？假如你的千兆服务器有1000个人同时观看视频的话 是不是每个人就只能分到1兆带宽了 我很有兴趣注册付费会员 但比较担心带宽在人多情况下没有保障 谢谢

**Comment by yanggis** [comment]
这个尽管放心，肯定不会有这种网络拥塞的情况，因为VPN版本本身的设计就是个少量用户、多服务器配置的。目前虽用户增加会不断增加新的服务器，保证每个用户用最好的视频体验。
