### ISSUE TITLE
云视听极光 应版权方要求暂不提供播放服务

### ISSUE THREAD

**Issue by sorrych** [yanggis/ChinaTunnel#168]
![20190112200815](https://user-images.githubusercontent.com/24655869/51073443-e2b14d80-16ab-11e9-9df1-6ad5ae755db9.jpg)

**Comment by sorrych** [comment]
芒果tv，酷喵正常

**Comment by sorrych** [comment]
@yanggis 方便的时候帮忙检测一下，感谢

**Comment by lixiaole022** [comment]
我也是这个问题，您微信多少？我想截图给您。
