### ISSUE TITLE
開機 顯示有連上WIFI 卻無法上網

### ISSUE THREAD

**Issue by wolfted** [yanggis/ChinaTunnel#17]
插上電源 第一次開機(冷開機) 會顯示有連上WIFI 卻無法連上網路
按下遙控器電源按鈕 選擇 重新開機(暖開機) 就可以連上網路
http://imgur.com/k4PxbOs

剛才把chinatunnel 移除後或關閉自動啟用，斷電並開機 試了幾次，都可以連上網路

1.7.6執行成功後還要詢問。比較喜歡1.7.3直接跳出

這是我寫的文章，假如您有用到，歡迎使用。我把chinatunnel 安裝並轉系統檔案預設開機啟動，都寫進去。
【小胖教學】小米盒子3 增強版 Root、ChinaTunnel完美翻牆 海外解決境外IP限制 、去除廣告、繁體化系統、YouTube台灣化 1/28整理
http://wolfted.blogspot.tw/2017/01/3-rootchinatunnel-ip-youtube.html

**Comment by yanggis** [comment]
你说的插上电源，第一次开机会无法连接上网路的问题我没有碰到过，这个应该和Chinatunnel没有关系，因为Chinatunnel没有对WIFI连接进行任何修改。
1.7.6執行成功後還要詢問是为了解决Android 5.1 TV版的Bug设置的，如果直接跳出会被立刻被系统后台杀死，导致不能在后台解锁。
