### ISSUE TITLE
Root版ChinaTunnel 將在2019年2月6日起暫停服務，會再開服嗎？這個軟件真心做得很好，為海外用戶解決了大陸的限制。

### ISSUE THREAD

**Issue by JanusPro** [yanggis/ChinaTunnel#170]

**Comment by yanggis** [comment]
ChinaTunnel开发之初是为了让海外华人观看大陆视频和听音乐用的，但是最近两年该APP逐渐被滥用，几乎所有的海外电视盒子销售商都会给自己的盒子安装ChinaTunnel，对ChinaTunnel服务器造成巨大压力，甚至直接移除我们在APP里内嵌的广告，对ChinaTunnel的正常运行造成巨大影响，因此我们才考虑暂停服务，敬请谅解。

**Comment by sinochinois** [comment]
做个root的收费版怎么样？vpn版本兼容性还有待提高

**Comment by yanggis** [comment]
@sinochinois 您是说小米盒子3的ROM兼容性有问题吗？这个现在我们正在调整，月底会发新版本。

**Comment by sinochinois** [comment]
好的好的👌

**Comment by JanusPro** [comment]
好吧，很感谢你
