### ISSUE TITLE
你好我買了年費一直連不上

### ISSUE THREAD

**Issue by okrexrex** [yanggis/ChinaTunnel#172]
你好, 我是用小米盒子3加強版,用了小米3專用版1.3.0,但是連不上
出現 Send Fd failed, 1.4.0版本閃退不能用.

我在ChinaTunnelVPN上填了工單,都沒人回覆我

**Comment by okrexrex** [comment]
你好, 我是用小米盒子3加強版,用了小米3專用版1.3.0,但是連不上
出現 Send Fd failed, 1.4.0版本閃退不能用.

我在ChinaTunnelVPN上填了工單,都沒人回覆我

**Comment by zhuhang-jasper** [comment]
我打算试用，行的话就充值，怎么知道什么都链接不上。
1.3.0 App 显示链接成功，但是网络连接不上。也不确定设置正不正确。（我用账号里显示的port和密码，试了 sfo, la, hongkong, tw2）但是电视猫视影全都看不了，没网络似的。

**Comment by okrexrex** [comment]
> @okrexrex 小米盒子的问题已经回复很多遍了，你稍微翻一下issues就知道，没必要重复回复,这个是小米盒子ROM的问题，会在下个版本里修复。
> @zhuhang-jasper 应该也是同样小米盒子3的问题。

謝謝你的回覆, 期待下個版本

**Comment by okrexrex** [comment]
哎1.5版本還是閃退用不了.......

**Comment by okrexrex** [comment]
@yanggis 好的謝謝, 我馬上試試, 之前1.3版本老是出現 Send Fd failed

**Comment by okrexrex** [comment]
@yanggis , 謝謝你, 但是還是不行, 出現 Send Fd failed

**Comment by yanggis** [comment]
@okrexrex 等我这周发新版本给您。

**Comment by yanggis** [comment]
@okrexrex 小米盒子3版本，可以下载了。
https://github.com/yanggis/ChinaTunnel/blob/master/chinatunnelVPN.1.5_for%20mibox3.apk

**Comment by okrexrex** [comment]
@yanggis  太感謝了
