### ISSUE TITLE
安博S900PROBT连线后没有流量

### ISSUE THREAD

**Issue by BigQiu85** [yanggis/ChinaTunnel#175]
盒子是安博S900PROBT,安卓版本5.1
看了先前的文装了ChinaTunnelVPN1.3.0的版本
添加完伺服器及参数密码确认后也显示已连线
但是在轻触以检查连线能力这测试就是连不上,奇异果打开也连不上
请问这该怎么处置?

**Comment by BigQiu85** [comment]
把所有节点全添加上了,坐标台湾,用的中华电信100M
目前右边纸飞机点下后显示连接成功,但是点了轻触以检查连线能力后显示无法使用网际网路

**Comment by yanggis** [comment]
@BigQiu85 这个我在检查，等下周发布一个新的版本应该就可以了。

**Comment by yanggis** [comment]
小米盒子3等旧盒子版本，可以下载了。
https://github.com/yanggis/ChinaTunnel/blob/master/chinatunnelVPN.1.5_for%20mibox3.apk

**Comment by yanggis** [comment]
最新版到1.6.0版本了
