### ISSUE TITLE
台灣愛奇藝

### ISSUE THREAD

**Issue by erisepapa** [yanggis/ChinaTunnel#176]
您好，

感謝你提供的服務，有個疑問可否幫忙解疑

傳統chinatunnel可以透過修改whitelist，配合自行架設web server，將台灣愛奇藝不進行轉跳觀看影音。

我目前購買了chinatunnelvpn 的授權，請問是否可以不跳轉愛奇藝的服務? 因為家人不懂複雜的測試，要來來回回控制有點麻煩。

**Comment by erisepapa** [comment]
感謝您的回覆

另外是否考慮出一版 apk 可以兼容 機上盒"遙控器"的操作
目前都要使用模擬滑鼠操控啟動/關閉 VPN

使用起來不是很順暢，可否改善操作流程

**Comment by yanggis** [comment]
@erisepapa 现在版本配置好用遥控操作也没问题，配置的时候可以接电脑键盘和鼠标，暂时不考虑更改界面。
