### ISSUE TITLE
看视频卡的受不了

### ISSUE THREAD

**Issue by BigQiu85** [yanggis/ChinaTunnel#179]
刚刚买的X96 Max盒子4G64G的 , 系统是安卓8.1 , 卖家说此盒子不用root , 坐标台北用的中华电信100M
日常使用的奇异果,微视听,芒果,腾讯 这些应用

1. 装了1.5.0后试了很多节点 , chinatunnelVPN内显示连线成功 , 测试连线延迟大概在300上下 , 但是看视频时都显示无法连线或网络有问题无法观看 .

2. 换回1.4.0后用了TW HK LA 的节点 , 平均看2~3分钟就开始转圈等待 , 有时很快缓冲能看或是直接说网络有问题或无法连线 , 需要回chinatunnelVPN内对节点中断然后再连线 , 几乎一直在无限循环 .

3. 用当贝市场自带的测速 , 速度时高时低飘忽不定且速度都不快 , 最快大概都只有3M惨不忍睹 , 猜想测速的反应完全跟看视频时状况一致 , 时高时低代表视频时顺时卡 . 

4. 有朋友们用安博S900PROBT测试过1.5.0版本了吗? 效果如何?

一直以来用chinatunnel搭配安博看的很开心 , 连线问题也不太多 , 于是在听闻chinatunnel即将收费并且推出chinatunnelVPN时觉得应该给予大力支持 , 于是买了新盒子也买了年费 , 希望团队能尽快帮忙解决 , 谢谢 .

**Comment by yanggis** [comment]
当贝测网速的时候记得关闭chinatunnelVPN，如果关闭VPN状态在测速还是忽高忽低，时快时慢，说明你自己本身的网络连中国大陆就很慢，和chinatunnelvpn没有任何关系。
无流量的问题以前已经说过了，是因为你本地DNS有问题，无法解析我们服务器的域名的IP，比如sfo.yanggis.com,通过ping这个域名得到的IP是104.236.184.163，你可以在chinatunnelvpn里面直接填这个IP就可以。Anyway，不管是网速还是打开VPN无流量，都是你本地网络的问题。
