### ISSUE TITLE
有可能移植到OpenWrt上吗？

### ISSUE THREAD

**Issue by homsai** [yanggis/ChinaTunnel#18]
目前用Dnsmasq还不错，不过QQ音乐不好用。我想知道有移植到OpenWrt的可能性吗？

**Comment by homsai** [comment]
看到过去的回复了。。。希望以后能支持或者开源方法，谢谢😜

**Comment by yanggis** [comment]
现在暂时没有计划，OpenWRT用户太少，不想在上面投入精力开发。
