### ISSUE TITLE
VPN版1.5 QQ音乐无效

### ISSUE THREAD

**Issue by lllinusss** [yanggis/ChinaTunnel#180]
在android手机上使用VPN版1.5， qq音乐还是有地区限制，使用穿梭app的话qq音乐可以正常播放

**Comment by yanggis** [comment]
谢谢反馈，我这两天检查一下。

**Comment by lllinusss** [comment]
我在手机上用1.60试了还是不行
________________________________

**Comment by yanggis** [comment]
@lllinusss 麻烦再试一下看看现在可以了吗？可以多打开关闭chinatunnelVPN翻墙服务试试。
