### ISSUE TITLE
VPN 1.5 旧盒子能用吗?

### ISSUE THREAD

**Issue by phillipouyang** [yanggis/ChinaTunnel#181]
如题.

**Comment by yanggis** [comment]
不能用，等这周发更新。

**Comment by yanggis** [comment]
新编译的小米盒子3版本，可以下载了：
https://github.com/yanggis/ChinaTunnel/blob/master/chinatunnelVPN.1.5_for%20mibox3.apk

**Comment by phillipouyang** [comment]
谢谢，请问海美迪h7 2代能用这个版本吗？一直用1.3

**Comment by yanggis** [comment]
应该是可以用

**Comment by phillipouyang** [comment]
谢谢
