### ISSUE TITLE
小米4盒子（1.60版本）

### ISSUE THREAD

**Issue by sololau00** [yanggis/ChinaTunnel#183]
1.我使用新加坡，香港服务器的时候无法使用可是我ping了一下很正常（50-100MS）。于是我获取Ip写入Chinatunnel还是不行。新加坡2和香港2的节点快但是在Chinatunnel测试了一下显示（新加坡2:2041-5000毫秒）（香港2:1700-4000毫秒）
开腾讯Tv，酷猫 都是加载图片和刷新特别慢。

2.连接的时候会卡住一下子（整个画面停止几秒）
3.点击设置选项 会闪退

**Comment by yanggis** [comment]
加载图片和刷新这个影响不大，连接的时候服务器需要帮你翻墙，需要几秒钟的时间，开始播放就比较顺畅了。

**Comment by sololau00** [comment]
观看时不会停顿很好😌，只是加载图片慢。
