### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by sololau00** [yanggis/ChinaTunnel#184]
有时候开始看的时候800kb-1.xMb，看到一半会停顿。

**Comment by yanggis** [comment]
是什么APP呢，腾讯云视听？

**Comment by sololau00** [comment]
对的

X.K. YANG <notifications@github.com>于2019年2月1日 周五下午11:07写道：

**Comment by yanggis** [comment]
用的是哪个服务器，新加坡2吗？

**Comment by sololau00** [comment]
台湾2

X.K. YANG <notifications@github.com>于2019年2月1日 周五下午11:09写道：

**Comment by yanggis** [comment]
停顿之后是网速比较慢，缓冲一会又可以播放了，还是停顿之后就再也不能继续播放了呢？

**Comment by sololau00** [comment]
台湾2使用chinatunnel测试了下500+毫米，新加坡2和香港2，比较高1000-4000毫米。看戏停顿后要等一下（1-2分钟吧）就继续跑。具体的还没什么去测试。

**Comment by yanggis** [comment]
这个是网速的原因，应该是台湾2在你当地连速度不够，不要看chinatunnelVPN的ping值测试，这个不是真实速度，没有代表性，你要多换几个服务器测试一下才能知道哪个服务器在你当地连接看视频速度是最快的。腾讯视频源可以先试试广州，深圳，洛杉矶等地的几个服务器。

**Comment by sololau00** [comment]
喔喔，好的我明天测试，只是现在服务器1的我测试不到ping值，ip也不行，连接后加载不到任何东西，密码对的，端口也是

X.K. YANG <notifications@github.com>于2019年2月1日 周五下午11:17写道：

**Comment by yanggis** [comment]
如果开始播放网速800k，基本上说这个服务器在你当地是慢的，正常情况下，刚开始播放速度可以达到3M/S以上，说明你当地链接这个服务器响应比较快，速度比较流畅。

**Comment by sololau00** [comment]
小米盒子4的Wifi连接最快只能3-4M/S，不支持有线的网络。

X.K. YANG <notifications@github.com>于2019年2月1日 周五下午11:21写道：

**Comment by sololau00** [comment]
应该吧🌚

Mr. FAKER-2017 <sololau00@gmail.com>于2019年2月1日 周五下午11:23写道：

**Comment by sololau00** [comment]
有可能是自己的路由器传输wifi慢？

Mr. FAKER-2017 <sololau00@gmail.com>于2019年2月1日 周五下午11:28写道：

**Comment by yanggis** [comment]
在盒子上安装沙发管家.apk，打开它，在设置里启动显示实时监控网速，然后打开企鹅云视听播放一个电视剧，看看实时网速是多少，找个最快的就好了

**Comment by sololau00** [comment]
好麻烦啊，我会尝试的👌

X.K. YANG <notifications@github.com>于2019年2月2日 周六上午1:20写道：
