### ISSUE TITLE
自建服务器透明代理的问题

### ISSUE THREAD

**Issue by dalvjin** [yanggis/ChinaTunnel#187]
小米盒子3增强版上root并 安装了chinatunnel 2.23 , 在国内自建了squid服务器 ，在自建服务器输入ip 和端口， 启动后 一直还是会出现版权 错误106， 透明服务器那边都很正常，在浏览器proxy设定后 ， ip地址显示国内地址， 不知道哪里出的错， 可以指点一下吗？

**Comment by yanggis** [comment]
chinatunnel的root版现在已经停止支持了，不在回答关于chinatunnel的root版的问题了。
