### ISSUE TITLE
小米盒子四闪退

### ISSUE THREAD

**Issue by WayeeWang** [yanggis/ChinaTunnel#190]
您好。以前一直用root版。现在装了vpn版后无法进去，白屏一秒后退出，1.5和1.6都试过了

**Comment by yanggis** [comment]
安装这个版本
https://github.com/yanggis/ChinaTunnel/blob/master/ChinaTunnelVPN-1.5_0204_for_mibox4.apk
如果还不能用，只能说明你自己的盒子ROM现在有问题，需要您自己排查问题。
