### ISSUE TITLE
海信电视 vidaa4 

### ISSUE THREAD

**Issue by cksjason** [yanggis/ChinaTunnel#192]
海信电视 vidaa4 ，创建vpn服务权限不足，无法使用，之前chinatunnel能正常使用

**Comment by cksjason** [comment]
1.5 1.6四个版本都试了，按连接的时候，显示创建vpn服务权限不足，电视已经root，之前使用免费版都正常，

**Comment by yanggis** [comment]
@cksjason 电视带的android是什么版本？其实建议你买一个一般的电视盒子配合电视使用，会比较好一些。

**Comment by cksjason** [comment]
电视新买的，andriod 6.0，能不能出一个和之前免费版一样，付费不是问题，最重要是能用

**Comment by cksjason** [comment]
另外有个电视盒子，乐视u2，Android4.4，已root的，下载了apk不能安装，显示剖析问题，之前免费版很好用，能不能在那个基础上加入收费功能

**Comment by yanggis** [comment]
@cksjason 抱歉，这个暂时没有这个计划。
