### ISSUE TITLE
泰捷webox 无法使用chinatunnel

### ISSUE THREAD

**Issue by carlosvivi2018** [yanggis/ChinaTunnel#195]
之前的乐视盒子和小米盒子2因为反应系统太旧了没有办法装新的chinatunnel，因此特地599人民币买了最新的泰捷盒子We40。
结果居然还是不能用，现在页面上有下载的1.5版本全部安装完成后白屏闪退，1.6版本显示的无法解析安装包。。。。求协助，不希望又花钱白买了盒子。。。

**Comment by carlosvivi2018** [comment]
用电视管家安装成功了1.6正常的版本，现在设置完成了登陆文件，也显示连接成功了（但电视上面似乎无法点击测试连接因为光标移动不过去）。
现在的问题是连接后按遥控器的主页按钮没有反应，按返回可以到盒子主菜单，然后打开爱奇艺仍然无法观看，原因应该是打开了爱奇艺后Chinatunnel就关闭了（并未在后台运作），重新点开又需要重新连接。。。

**Comment by carlosvivi2018** [comment]
还有就是按配置选项，也会闪退

**Comment by yanggis** [comment]
泰捷盒子We40的系统是阉割版的，没有后台VPN模块，自然就没法运行VPN软件，看来你只有退货了。
