### ISSUE TITLE
ChinaTunnelVPN1.6.0 无法在小米盒子2代上安装

### ISSUE THREAD

**Issue by johnsmith351** [yanggis/ChinaTunnel#196]
二代小米盒子（又称新小米盒子），硬件版本MDZ-06-AA，操作系统Android 4.4.2。尝试安装即报解压缩出错。请问有没有计划支持二代小米盒子？谢谢。

**Comment by ted0222** [comment]
同问 几天试了所有种安装包 连电脑安装 本地安装 都不行啊 我这异国他乡的 快疯了

**Comment by yanggis** [comment]
抱歉，设备太老了不支持，建议amazon或者ebay上买个便宜的外贸盒子，或者小米盒子，或者sheild TV等。
