### ISSUE TITLE
Open source ChinaTunnel

### ISSUE THREAD

**Issue by zmingxie** [yanggis/ChinaTunnel#2]
@yanggis 请问你打算把这个app开源吗？我对这挺有兴趣的，想多了解一下代理是怎么配置

**Comment by yanggis** [comment]
@zmingxie 您好，暂时没打算开源，因为这个仅仅是实验性的。我想在此基础上开发另外一个项目解锁软件。到时候会开源那一个。

**Comment by zmingxie** [comment]
好的！我觉得这样的解锁软件能开源最好，大家可以一起维护，互相帮助！:-)

**Comment by yanggis** [comment]
感谢建议，我会认真考虑你的建议！

**Comment by kimyu92** [comment]
我同意 @zmingxie, 支持开源一起维护。而且，如果需要维持服务器经费，可以搞捐款或众筹。

**Comment by tzyking** [comment]
众筹顶一个！

**Comment by yanggis** [comment]
@kimyu92 @tzyking 谢谢建议，众筹的事情等我计划一下。

**Comment by yanggis** [comment]
@kimyu92 @tzyking 能提供一下哪个众筹网站比较靠谱吗？

**Comment by kimyu92** [comment]
- [kickstarter](https://www.kickstarter.com/)
- [indiegogo](https://www.indiegogo.com/)
- [bounty source](https://www.bountysource.com/)

**Comment by yanggis** [comment]
@kimyu92 谢谢
