### ISSUE TITLE
和优酷有关的资源好像无法观看

### ISSUE THREAD

**Issue by sihot** [yanggis/ChinaTunnel#20]

**Comment by yanggis** [comment]
你用的是android手机的优酷客户端APP，还是电视盒子的优酷视频XL or CIBN环球影视？

**Comment by sihot** [comment]
电视盒子优酷视频XL

**Comment by sihot** [comment]
而且别的客户端只要是链接 优酷资源的 都无法打开

**Comment by yanggis** [comment]
电视盒子优酷视频XL安装最新版的5.1.5版本，
chinatunnel用最新版的1.7.6，更新whitelist

我刚才已经试了，可以播放，没有任何问题。

**Comment by sihot** [comment]
还是不行 errorCode:400001:2:5

**Comment by yanggis** [comment]
你用的是哪个服务器？新加坡的还是北美的？
http://ip.cn/
显示你的IP是多少？

**Comment by sihot** [comment]
65.29.178.220

现在用的新加坡

**Comment by yanggis** [comment]
嗯，我现在再检查一下服务器

**Comment by sihot** [comment]
北美服务器 可以观看了

**Comment by yanggis** [comment]
如果你在北美地区，尽量用北美地区的服务器，因为从北美到新加坡距离太远，高峰期丢包比较严重，造成新加坡这边收不到你发来的解锁请求，所以就解锁不了。

**Comment by sihot** [comment]
懂了，谢谢

**Comment by sihot** [comment]
有个问题请教一下，既然服务器都在中国，那为什么还要分东南亚和北美？

**Comment by yanggis** [comment]
因为客户分布在世界各地，不见得每个人都可以和中国的服务器通讯顺畅，尤其中国的糟糕的网络环境下。通过在国外优质网络上设置CDN节点，使所有的请求经过优质网络通道进入中国就可以保证解锁的速度和可靠性。
