### ISSUE TITLE
看不到B站

### ISSUE THREAD

**Issue by fw1010** [yanggis/ChinaTunnel#201]
最近这几天用China Tunnel 3.0 都看不了B站(云视听小电视)，会显示"-5:connect error"。麻烦您看看，谢谢!

**Comment by yanggis** [comment]
好的，谢谢，我检查一下。

**Comment by yanggis** [comment]
您用的是哪个服务器？还是所有服务器都这样报错呢？

**Comment by fw1010** [comment]
刚试了所有的服务器, 都会报这的样错.

**Comment by yanggis** [comment]
好的，谢谢反馈，我们正在修复。@fw1010 您有微信吗？方便我加一下您吗？

**Comment by fw1010** [comment]
有. 但如何私下发给您? 在这里公开发给您不太好.

在 2019年2月21日週四 11:05，X.K. YANG <notifications@github.com> 寫道：

**Comment by fw1010** [comment]
您应可以看得到我的电邮地址吧? 您发个私人电邮给我, 我就可以私下回您我的微信号.

**Comment by yanggis** [comment]
@fw1010 不好意思看不到，您发邮件到chinatunnelvpn@gmail.com告诉我一下您的微信号吧，谢谢。

**Comment by fw1010** [comment]
已回. 请查收. 谢谢!

**Comment by fw1010** [comment]
可以了，要您工作到这么晚把问题解决，太感谢了!!
