### ISSUE TITLE
TV盒子和手机都连上了，但是没有流量

### ISSUE THREAD

**Issue by SwiftGraff** [yanggis/ChinaTunnel#205]
我是新用户，之前测试时可以，但是重新注册充值后，连接没有流量，TV盒子和手机都是一样。
服务端口是20351，请帮我查看一下，谢谢！

**Comment by yanggis** [comment]
您好，刚才查看了您的账号正常，麻烦把chinatunnelvpn卸载，重新安装一下最新版1.8.0版本再试试，如果有问题请在这回报，我们会持续跟踪解决。

**Comment by SwiftGraff** [comment]
我重新注册了一个号，正常了，我又充值了，端口号是26713。原来那个20351真不行，能退费吗？

X.K. YANG <notifications@github.com> 于 2019年3月5日周二 19:48写道：

**Comment by yanggis** [comment]
@SwiftGraff 可以的你用付费的微信或者支付宝发个信息，可以直接退。

**Comment by yanggis** [comment]
已经处理了。
