### ISSUE TITLE
真心希望作者能做一个旧版app那种模式，收费是没问题的。

### ISSUE THREAD

**Issue by lukeliu123** [yanggis/ChinaTunnel#212]
现在版本的app，界面太复杂，且太纠结于手机了。大多数情况大家都是给家里盒子用的，也就是用遥控器的多。以下是我的建议：
1. 为每个节点直接在app中加入设定，也就是都设定好。我们只需要输入账号，以及密码一次就行了。 （目前我们每次卸载重装，就要重新输入所有节点，密码，账号，遥控器输入非常之麻烦。并且账号密码都是一样的，重复输入太傻了。）

2.界面操作，着重于tv，盒子用户。比如说类似旧版，一键傻瓜操作，老人开心，我们开心。按钮选中的反色要明显，现在那个真的很难看清楚在哪里，上下左右也很难移动到按钮上面。（现在的明显是手机app，我们不反对手机用户，但是不能完全放弃盒子用户。）

3.root功能保留。大部分人都是老用户了，也就是盒子带root的。既然带root，就希望加入类似旧盒子那样傻瓜模式。难度应该不大吧？

4.收费模式。为什么用旧款chinatunnel，一点是免费，另外一点就是方便，简单。市场上收费的vpn用起来都非常的麻烦。并不是钱的问题。希望作者能做一个操作容易的vpn，让大家用起来就像老版chinatunnel那样最好了。收费是完全没问题的。

**Comment by yanggis** [comment]
旧版本的chinatunnel是经过三年才不断改进完善的一个产品，chinatunnelVPN才有几个月的时间，肯定会需要时间以及结合用户反馈不断完善，不可能一下子完全做好，好的产品需要你的耐心和支持。
目前新版本也就是电视盒子配置参数的时候比较麻烦，但是配置参数的时候完全可以接个鼠标配置参数，配置完成把鼠标拔掉就好了。每次启动基本都是遥控操作就行了。
