### ISSUE TITLE
奇異果不能看

### ISSUE THREAD

**Issue by fish7yu** [yanggis/ChinaTunnel#214]
您好，昨晚發現小米盒子3上不能看奇異果，騰訊視頻是OK的。  麻煩請測試確認一下。

**Comment by yanggis** [comment]
您好，感谢反馈，提示是什么问题呢？

**Comment by fish7yu** [comment]
您好，並沒有提示，就是視頻無法播出。

重新開機後現在正常可看了，謝謝!
