### ISSUE TITLE
小米盒子s 國際版

### ISSUE THREAD

**Issue by chourete** [yanggis/ChinaTunnel#215]
請問小米盒子s能夠使用嗎？ (Android 8.1)
載了各種版本 APP中有顯示已經連上 但是去查看IP都還是處於在台灣的狀態，中國APP也一樣受限制

有試過 X梭 X帆 ChinaTunnel ，都有一樣的問題，不知道是不是因為ANDROID版本的問題 

還是小米盒子s本身遮蔽了VPN呢

**Comment by yanggis** [comment]
您好，这个应该是小米盒子系统的问题，有可能是小米禁止了VPN模块。
