### ISSUE TITLE
Smart Youtube TV 連線問題反饋

### ISSUE THREAD

**Issue by erisepapa** [yanggis/ChinaTunnel#216]
Smart Youtube TV 
https://smartyoutubetv.github.io/

目前家裡機上盒使用此APP觀看 Youtube影片。(整體的使用者畫面比較習慣)

搭配VPN啟動時，載入影片會稍微停頓或無限的等待載入中
稍微停頓還可以接受，但無限的等待載入就比較困惱

可否幫忙確認修改此問題。謝謝。

PS: 關閉VPN時，可以瞬間秒開影片。

**Comment by yanggis** [comment]
您好，谢谢反馈，您是用chinatunnelvpn什么版本呢？

**Comment by erisepapa** [comment]
你好，目前使用chinatunnelVPN-1.8.0_for_phone_0324.apk

**Comment by yanggis** [comment]
好的，谢谢反馈，我检查一下看看什么问题。

**Comment by erisepapa** [comment]
經過這陣子使用，回報發現的現象

1. 剛啟動VPN，馬上看Smart Youtube，順利觀看影片
2. 開啟VPN連線超過一段時間，未觀看(因為機器都沒有關機)，看Smart Youtube 有"可能"發生問題
   此時 銀河奇異果/騰訊雲視聽 也會"可能"無法順暢觀看 => 估計是 閒置時間過長，造成被伺服器主動斷線。若馬上重新連線VPN，也有"可能"仍然無法觀看。此時需要重開機器才會恢復。

請麻煩看這種現象是否能解決。謝謝

**Comment by yanggis** [comment]
@erisepapa 您好，谢谢反馈，请问您用的什么设备呢？

**Comment by erisepapa** [comment]
你好，我的機器是 Himedia Q5 OEM 海外版
https://www.himedia-tw.com/product/Q5IV-cn.html

**Comment by yanggis** [comment]
谢谢回复，您的系统是android 7.0吗？

**Comment by erisepapa** [comment]
是的~ android 7.0

**Comment by yanggis** [comment]
您安装的是1.8.0版本吗？用的是哪个服务器呢？

**Comment by erisepapa** [comment]
版本是 chinatunnelVPN-1.8.0_for_phone_0324.apk
伺服器是 tw2

**Comment by yanggis** [comment]
@erisepapa 谢谢回复，您有没有尝试换其他服务器试试呢？比如旧金山或者硅谷的服务器。

**Comment by erisepapa** [comment]
好的，我在台灣，基本上都用tw2，因為反應速度較快

我會試試看其他伺服器。有相關結果再來回報! 或你有想讓我測試哪個伺服器也可以，麻煩提出。

**Comment by abigchopstick** [comment]
我感觉是SMARTYOUTUBE TV自己的问题，好像他不是直接连YOUTUBE一样，我用其他翻墙软件，在电脑上可以看4K YOUTUBE，还是秒开，但在SMART YOUTUBETV上就不行。

**Comment by ilex2023** [comment]
![1701940540687](https://github.com/yanggis/ChinaTunnel/assets/137477954/fe9d2b27-7537-4ecf-9194-95fc084140cf)

你好，我一直在使用Smarttube TV这个应用。其他的都很不错，但有两个问题总是困惑着我：
1. 在OLED电视上，在电视最中心的一小块区域总是被白色的标题占用，故很容易造成OLED屏幕的烧屏现象，我的OLED电视现在已经开始烧屏了，只不过不是那么明显。
2. 无法像官方应用一样播放视频时显示连接网络的连接速率。

**Comment by jindapeng777** [comment]
你好！我最近使用软件过程中出现节点是正常的情况下，软件无法播放并出现下面图片里的提示，请求帮助找到问题所在，观看YouTube时的节点使用其他软件并不会出现问题。

![IMG_0346](https://github.com/yanggis/ChinaTunnel/assets/131684387/4a1a4287-bc87-4ac3-9e1a-6a892c74ba99)
