### ISSUE TITLE
Mac 和 iOS 版本什么时候出？

### ISSUE THREAD

**Issue by BookmanHan** [yanggis/ChinaTunnel#220]
用了一下这个软件，觉得真是不错。
速度不能上 1080p，但 720p 完全没有压力。
价格也便宜，三个月才 40 块。

可以考虑推出高级会员，价格稍微涨一些，但能看 1080p。
希望推出 Mac 和 iOS 版本。

**Comment by yanggis** [comment]
您好，您可以多换几个服务器，找个在您那边服务器最快的1080p应该是没问题的。价格仅仅是为了支付服务器的流量费，不会再上涨了。后续mac版本会再有更新。
