### ISSUE TITLE
無法連線遠端服務器。小米盒子。

### ISSUE THREAD

**Issue by dippgotsai** [yanggis/ChinaTunnel#224]
用了一段時間，到昨天用還好好的。今天突然就不行了！  更新也是一樣狀況，台灣節點 洛杉磯節點都試過了。一樣都是出現無法連線遠端服務器。更正一下 我使用的是小米電視 不是盒子

**Comment by yanggis** [comment]
您好，谢谢反馈，启动VPN的时候提示无法连接远程服务器吗？

**Comment by dippgotsai** [comment]
您好。是的。啟動VPN 時跳出的錯誤訊息

**Comment by yanggis** [comment]
您好，您在小米盒子设置里面找到应用，找到chinatunnelvpn,把chinatunnelvpn清空设置和缓存，然后重新配置试试？估计是因为缓存的问题引起的。
