### ISSUE TITLE
小米盒子4 SE版

### ISSUE THREAD

**Issue by chuin1975** [yanggis/ChinaTunnel#225]
打开软件，完成设置选项后，然后点橙色按钮启动VPN服务， 程序闪退
已尝试按装 chinatunnelVPN-1.8.0_for_mibox4_0324  和 ChinatunnelVPN-1.8.0_for_mibox3_0324.apk，都有同样的问题，求解

**Comment by yanggis** [comment]
您有没有安装一下1.5或者1.7版本试试呢？

**Comment by chuin1975** [comment]
已尝试 ChinatunnelVPN-1.6.0_for_mibox3，ChinatunnelVPN-1.7.0_for_mibox3 和 chinatunnelVPN-1.5_for_mibox4，当点击橙色按钮启动VPN服务， 程序会闪退

**Comment by yanggis** [comment]
额，好吧，估计您的小米盒子的系统是阉割版，没有VPN模块。。。。

**Comment by chuin1975** [comment]
谢谢
