### ISSUE TITLE
優酷視頻(非電視板的喵酷)無法播放

### ISSUE THREAD

**Issue by lawrenceysl** [yanggis/ChinaTunnel#230]
分別用了1.8 及 最新的2.0 china tunnel 開啟優酷視頻後，優酷直接彈出視窗 "訪問被拒絕，請檢查是否使用了VPN",  然後無法播放視頻。  已嘗試轉換其他訪問點，eg: dg.yanggis.com ;  sz,  ;  bj.  等，也沒法解決。  相反，電視端(喵酷視頻) 則可以訪問及播放視頻，但速度很慢。  請代為查看問題在所，謝謝。!

**Comment by yanggis** [comment]
优酷视频的检查是看你自己的手机上有木有开启VPN服务，和chinatunnelvpn没关系，就是随便开个其他的VPN服务也会报这种警告。

**Comment by yanggis** [comment]
酷猫请尝试伦敦的服务器，并把播放视频分辨率调低一点就可以流畅播放了。

**Comment by lawrenceysl** [comment]
謝謝!

**Comment by yanggis** [comment]
您也可以换个我们别的服务器试试
