### ISSUE TITLE
xgimi H3 Projector Android TV

### ISSUE THREAD

**Issue by bigboybig2019** [yanggis/ChinaTunnel#232]
我尝试所有新的每个版本 ,閃出來不能打开.

**Comment by bigboybig2019** [comment]
chinatunnelVPN.2.0.1所有版本閃出來不能打开.

**Comment by yanggis** [comment]
@bigboybig2019 那是因为你的设备有问题，设备的android系统是阉割版的，把vpn模块移除了，vpn服务没法在你设备上运行。
