### ISSUE TITLE
Amazon Fire TV 4K - libss-local exits too fast exit code 255

### ISSUE THREAD

**Issue by mikelei1997** [yanggis/ChinaTunnel#237]
您好，我的设备是Amazon Fire TV 4K, OS Version: Fire OS 6.2.6.6
前几天用1.4.0版本的chinatunnel还好好的，今天突然就没法用了，连接成功但是test connection的时候会出现ssl handshake aborted...connection reset by user之类的，而且会让WiFi连不上，直到把chinatunnel force stop了才好，试过1.8版本也是一样的问题。如果是2.0版本就会出现标题的libss-local exits too fast exit code 255错误。
个人怀疑是最近6.2.6.6版本的问题，因为之前没问题的时候都是6.2.6.5，最近更新后就出问题了，请问您那边有类似的设备可以尝试reproduce一下吗？我打算也往Amazon那边反映下看看

**Comment by yanggis** [comment]
您好，谢谢反馈，这个暂时没有，您可以试试安装1.5或者1.7版本试试，一般这种情况都是系统ROM的问题造成的。

**Comment by mikelei1997** [comment]
看了下amazon developer forum那边，官方不支持使用vpn所以不能指望他们来弄了。希望如果您有时间的话，可以测试下fire os的兼容性吧，这也算是大厂出的android tv，在海外的朋友应该也有用这个的。
