### ISSUE TITLE
小米盒子3增强板chinatunnelVPN无法使用

### ISSUE THREAD

**Issue by mu760905** [yanggis/ChinaTunnel#241]
![IMG_20200115_123954](https://user-images.githubusercontent.com/40752939/72484853-b42afd00-3840-11ea-827e-f6d68f3582d9.jpg)
![IMG_20200115_124218](https://user-images.githubusercontent.com/40752939/72484854-b4c39380-3840-11ea-961e-c9293fa369c6.jpg)
![IMG_20200115_124238](https://user-images.githubusercontent.com/40752939/72484856-b55c2a00-3840-11ea-9645-fc1e3ab9a40d.jpg)
你好，我的小米盒子3增强板已经还原+三清，只安装chinatunnelVPN.2.0.1-for_mibox3_0830.apk这个版本，无ROOT，小米盒子版本为1.5.93(稳定板)，输入服务器端口和密码也可以正常连线及Ping，但是观看时会出现错误码(601,-50)，每个地区都有连线过如la，tw2，gz，sz等等..但都会出现错误码，也有降版本使用ChinatunnelVPN-1.8.0_for_mibox3_0324.apk，一样不行，我的服务器端口为28953，请帮我确认一下，谢谢

**Comment by yanggis** [comment]
您好，请检查您的链接密码是否正确，您的链接密码的最后一位是L的小写l,不是字母i的大写I，也不是数字1。配置密码错误是不允许接入服务器的。
