### ISSUE TITLE
2.1.0版本连接图标有个bug？

### ISSUE THREAD

**Issue by itsmeoscar** [yanggis/ChinaTunnel#242]
我用的是手机版，以前右下角那个橘黄色的连接图标，点完后，会变成绿色。但是2.1.0版本还是橘黄色。底下的状态栏显示的是connected.

不知道这是不是个bug?

Thanks!

**Comment by yanggis** [comment]
您好，不是bug，2.1.0改了配色方案，一直都用橘黄色图标了。

**Comment by itsmeoscar** [comment]
哦，这样的话不是很明显啊，一开始还以为怎么一直没连接上，后来看下面才知道已经connected了，个人感觉变成绿色会清晰一些

**Comment by yanggis** [comment]
额，这个可能是需要一个视觉转变，因为有文字显示已连接，所以颜色显示就没太大必要，另外这个也是为了考虑到TV版遥控操作用户的方便，用户用遥控操作的时候当遥控选中这个开始按钮的时候，按钮会变成绿色，然后按OK键就可以启动服务器；通过颜色变化来提示遥控是否选中了开始按钮，这样电视盒子用户使用起来会更方便一些，要不然很难知道遥控是否选中了这个按钮，操作很麻烦。
