### ISSUE TITLE
极米H3 投影仪 GMUI系统是否有可用版本呢？

### ISSUE THREAD

**Issue by kkkkint** [yanggis/ChinaTunnel#243]
国内版没有google框架，是否有可用的版本？谢谢

**Comment by yanggis** [comment]
没有Google框架也不影响，只要有系统带有VPN模块就可以用，您有没有安装现在的2.1.0版本试试？

**Comment by kkkkint** [comment]
谢谢！试了几个通用版本都不行。网上查了下发现问题应该是极米H3的系统没有VPN功能。。。

**Comment by yanggis** [comment]
OK,那就没办法了，其实您可以在Amazon上买个国产的外贸电视盒子然后接到投影仪上用，这样会更方便。
