### ISSUE TITLE
账户问题

### ISSUE THREAD

**Issue by xiaocaotmw** [yanggis/ChinaTunnel#246]
若只有一个账户，能同时或分别注册在数个手机或平板上吗？

**Comment by yanggis** [comment]
在同一个IP下可以同时在三个设备上使用，多IP使用会被封账号。

**Comment by xiaocaotmw** [comment]
那是不是说，同一个账户，在自己住家里可以最多在三个设备上设置ChinaTunnel，是没有问题的?

**Comment by yanggis** [comment]
是的。
