### ISSUE TITLE
不知是否能支援PC上的chrome

### ISSUE THREAD

**Issue by kaiyuan0119** [yanggis/ChinaTunnel#247]
購買的是為了小米盒子使用，但是在大多數情形，還是以PC上chrome直接開啟如愛奇藝等使用環境較多。想請問不知道能否支援類似的使用環境，或是有沒有辦法透過proxy / VPN 插件等在chrome下使用呢？謝謝

**Comment by yanggis** [comment]
您好，现在在开发这一块内容，后面会有发布。
