### ISSUE TITLE
旧型号的小米盒子究竟应该用哪个版本的apk

### ISSUE THREAD

**Issue by maokaiyi** [yanggis/ChinaTunnel#248]
旧型号的小米盒子，小米盒子mini和小米盒子增强版（小米盒子3之前的型号），我应该下载哪个版本的apk软件。我看有3种，小米盒子3专用，小米盒子4选用，还有for phone。这三个有什么区别，我应该根据什么来判断选择哪个版本呢。

**Comment by yanggis** [comment]
您好，没有太大区别，小米盒子4那个版本就可以安装，如果您安装有旧版本需要先卸载旧版。

**Comment by maokaiyi** [comment]
谢谢回复，但是我发觉在我的小米盒子上无法安装，提示解析软件包时出现问题的错误，3个安装包都不可以安装。是不是lib文件的问题呀？同样的程序，我在我另一个Amazon
fire tv上可以安装并使用。我想在我的小米盒子上使用，有什么办法吗？

2020年4月5日(日) 14:07 X.K. YANG <notifications@github.com>:

**Comment by yanggis** [comment]
您好，如果fire tv可以安装就说明安装包没问题，应该是小米盒子本身的问题，您可以把小米盒子恢复出厂设置再安装试试呢？

**Comment by maokaiyi** [comment]
恢复了出厂设置了还是不行，是不是安卓版本的问题，有没有老版本的apk给我试试呢

**Comment by yanggis** [comment]
您的小米盒子android系统是什么版本的呢？

**Comment by maokaiyi** [comment]
可能是4.4.2的，我看你以前的回帖，貌似那时候不支持这个版本的安卓系统，现在这个最新版本也不支持吧

**Comment by yanggis** [comment]
您好，抱歉，这个系统太老了，现在已经不支持了。

**Comment by maokaiyi** [comment]
昨晚通过微信支付进行了充值，但是会员信息里的余额并没有反应出来，无法购买套餐，已经发了工单进行咨询，请帮忙确认，谢谢

**Comment by yanggis** [comment]
您好，现在已经到账，请查看您的账号余额。

**Comment by maokaiyi** [comment]
谢谢啦，已经看到余额了
