### ISSUE TITLE
Any one 今天4th/June有无法在小米盒子上播放的问题吗？

### ISSUE THREAD

**Issue by 13272150** [yanggis/ChinaTunnel#25]
你好·yanggis，非常感谢你开发这个软件造福版上其他网友们使用。你这帖药不错，及时解决我在境外无法使用小米电视盒的困扰。

我使用了快一年有余了，一切如旧正常完美。可是就在今天我发现药效好像失效了，我想问一下版上其他网友们，有无同样事情发生？

谢谢

p.s. 这么棒的软体，如果有需要直接的捐赠，我愿意贡献一份心意，谢谢大大，衷心希望这么好用的软件可以长长久久

**Comment by yanggis** [comment]
嗯，今天晚上六点半到八点半国内服务器停了两个小时，现在应该恢复正常了。

**Comment by yanggis** [comment]
感谢您的反馈，这个APP会持续维护下去，欢迎有问题及时反馈给我。

**Comment by 13272150** [comment]
谢谢你的回复，杨大~~

一切正常依旧，超级棒。谢谢
