### ISSUE TITLE
账号问题

### ISSUE THREAD

**Issue by LeoAkiraCN** [yanggis/ChinaTunnel#250]
你好我刚付费的账号今天说是被锁住了。账号只在家里的小米盒子用过wenjie.du@hotmail.com
在用户那里找不到任何可以反馈信息的界面。请帮忙查一下。

**Comment by yanggis** [comment]
您好，您的账号已经于6月16号过期了。

**Comment by LeoAkiraCN** [comment]
> 您好，您的账号已经于6月16号过期了。

您好，支付记录显示我是2020年6月11日，支付的250RMB，6月16号就过期了吗？
另外账户上写的是被管理员禁止了，目前无法通过那个账号，操作任何东西(所有按钮都不能点击) 。

**Comment by yanggis** [comment]
您好，您充值之后没有购买套餐，现在已经启用您的账号了，登陆购买套餐就好了。
