### ISSUE TITLE
[極光TV]解析影片不順暢

### ISSUE THREAD

**Issue by erisepapa** [yanggis/ChinaTunnel#252]
最近幾個月發現用 

Himedia 盒子+ 極光TV(騰訊雲視廳)，點部分影片開始撥放至少要等 30s 以上才能開始撥放，解析時間很久
搭配 銀河奇異果(愛奇藝 TV)版  解析很順暢

換了幾個伺服器測試現象依舊。

用手機 + 騰訊視頻，卻都很順暢。

請問我要如何改善 騰訊 極光TV解析速度呢?

**Comment by yanggis** [comment]
您好，您是在哪个国家呢？

**Comment by erisepapa** [comment]
台灣

**Comment by yanggis** [comment]
好的，我现在测试一下。谢谢。

**Comment by yanggis** [comment]
您好，这两天我们这边反复测试没有问题啊，现在还是解锁不顺畅吗？

**Comment by yanggis** [comment]
无反馈关闭

**Comment by erisepapa** [comment]
這兩天使用解析正常，先行關閉，待有問題再反饋

**Comment by yanggis** [comment]
好的，谢谢。有问题再反馈。
