### ISSUE TITLE
小米会员视频和云视听会员视频都播放不了，包块免费视频

### ISSUE THREAD

**Issue by ppeng11** [yanggis/ChinaTunnel#263]
最近小米会员视频和云视听会员视频都播放不了，包块免费视频！感觉像是小米跟云视听的server完全断线，请问是VPN的问题还是他们的问题？请问在内地的朋友有遇到类似的问题吗？谢谢！

**Comment by yanggis** [comment]
您好，现在还有问题吗？

**Comment by ppeng11** [comment]
问题还在！正常情况下就算不连接VPN也能播放小米或云视听的免费视频，但是现在都播放不了，确认过小米盒子4可以播放Smart YouTube TV在不连接VPN时。怀疑问题在小米跟云视听身上，只是想了解其他人是否有遇到类似问题！

**Comment by ppeng11** [comment]
问题已解决！是VPN会员的问题，感谢您！

**Comment by ykahhoo** [comment]
我的无法播放呢？要如何解决

**Comment by ykahhoo** [comment]
能为我解决吗？我本来可以观看的云视听会员，现在VPN链接了都看不了了。往常都没事，突然这个星期看不了。

**Comment by yanggis** [comment]
> 能为我解决吗？我本来可以观看的云视听会员，现在VPN链接了都看不了了。往常都没事，突然这个星期看不了。

您好，您换换服务器试试。可能是您现在用的服务器有问题。
您用的是哪个服务器？

**Comment by ykahhoo** [comment]
我使用tw或者tw2都不行

**Comment by yanggis** [comment]
换sfo或者la试试。

**Comment by yanggis** [comment]
tw2最近在维护，应该过三四天会恢复。到时候您可以再换回来。

**Comment by yanggis** [comment]
现在tw2已经可以了，可以再换回去试试。

**Comment by ppeng11** [comment]
請先確定VPN會員沒到期，過期後會什麼都看不了！

Best regards,
Peter Peng
+886 921980554

X.K. YANG ***@***.***> 於 2022年3月27日 20:12 寫道：

﻿

现在tw2已经可以了，可以再换回去试试。
