### ISSUE TITLE
密码忘记了，系统说已发送，可未收到

### ISSUE THREAD

**Issue by byekitty254** [yanggis/ChinaTunnel#265]
您好，我想续费，可是忘记密码，系统说密码已发送，几小时后依旧没有，请帮忙解决。

**Comment by yanggis** [comment]
您好，您可发邮件给我们客服人员chinatunnelvpn@gmail.com

**Comment by boknowswiki** [comment]
@yanggis ， 我也遇到同样的问题，而且我发了好多次邮件，都没有人回复我。
