### ISSUE TITLE
密码忘记了，系统说已发送，可未收到

### ISSUE THREAD

**Issue by boknowswiki** [yanggis/ChinaTunnel#268]
您好，我想续费，可是忘记密码，系统说密码已发送，几天后依旧没有，请帮忙解决。
我也发邮件给·chinatunnelvpn@gmail.com·， 我发了至少5封邮件，好几周过去了还是没有人回复。

**Comment by yanggis** [comment]
我们给您回复了呀，您看看是不是回复邮件被当做垃圾邮件拦截了啊？

**Comment by boknowswiki** [comment]
@yanggis , 应该不会的，因为我没有安装拦截邮件的应用，而且我也查看了所有的收件箱包括（垃圾邮件箱）。我同一个邮箱是不能再注册了是吗？你看这种情况我们怎么处理？谢谢。

**Comment by boknowswiki** [comment]
@yanggis , 我刚刚看了一下我的邮箱设置，确实没有问题。而且我可以收到你们的过期提醒。可是你们的重置密码的邮件我收不到。而且你说你回复我的邮件我也没有看到，我看到去年的时候你回复的邮件我都可以看到。

**Comment by yanggis** [comment]
@boknowswiki 告诉我您的邮箱，我在让后台查一下。

**Comment by boknowswiki** [comment]
@yanggis , 谢谢你的回复，我刚刚在邮箱中回复你了，麻烦你看下。谢谢。

**Comment by boknowswiki** [comment]
it works now. thanks.
