### ISSUE TITLE
盒子上使用无效

### ISSUE THREAD

**Issue by xman099** [yanggis/ChinaTunnel#3]
一开始想用在电视盒上，杂牌，6.0.1系统，已root
正常运行后，试了全聚合，腾讯，电视猫，能看的还是能看，不能看的依旧不能看，但是没有任何提示
后来手机上也装了试试看，也是6.0.1，正常运行后，全聚合基本都能看
关闭tunnel以后，提示所在地区不能看
不知什么原因，是battery optimization？

另外proxy location是什么意思？我两个都试过似乎没什么区别
多谢了

**Comment by yanggis** [comment]
你的那个杂牌的电视盒子很可能用的是CyanogenMod定制的android系统，这个android系统的内核文件有问题，但是不是所有版本都有问题，只是你刚好撞上了一个有问题的版本。你可以试试换刷一下这个盒子的用的android其他版本，比如5.1的，或者6.0，甚至同样是6.0.1，只是在不同时间编译的都可以。多试几个就能找到一个内核没问题的了。
通常在手机上可以用，换盒子上不能用几乎可以肯定是盒子的android内核文件有问题，已经碰到多次这样的情况，基本都是换刷其他版本就可以解决。

**Comment by xman099** [comment]
多谢回复。
盒子是Mini M8S II， 原生就是6.0.1，不过我确实找到几个不同日期的版本，我今晚刷下看看。

**Comment by yanggis** [comment]
您有没有尝试禁用电池优化选项试试啊？

**Comment by xman099** [comment]
我昨天试了另外一个unofficial的版本，vst一开始也是播放不出来，中间走开一段时间，回来发现竟然开始播了，只是相当卡。我试了其他电视剧，发现大部分确实能播，只是有些连接速度相当慢《w两个世界》，如果清晰度选的很高，开始的缓冲就是无限等待，少数稍等就能播（《胭脂》《麻雀》），即便是选高清蓝光也不会缓冲太久。所以我在想可能第一个内核版本也是可行的，只是缓冲太久而已。不过我的网络还凑合（comcast 50mbps），盒子的无线很一般，但是绝对够用，应该是片源的问题。

另外，盒子上是没有电池优化的选项，因为本身没有电池。。。这个是我忽略了。

多谢yanggis的回复，之后会继续反馈。

**Comment by yanggis** [comment]
@xman099 感谢反馈，麻烦您这几天多用几次，然后总结一下规律，看看大概哪些会有这种情况。现在会有这种情况，就是VIP的源刚开始会连接比较慢，这个是因为VIP有好几个套验证程序，需要全部都完成才能开始播放，找个验证比较繁琐，会耽误点时间。但是一旦开播了之后2-3分钟应该就会正常了。您再找一下规律，有规律的话我就容易找问题来修复它了。非常感谢您使用chinatunnel.

**Comment by xman099** [comment]
我周末用了一下，发现几个问题： 正常运行以后，其他app的信息页面会受到影响，比如视频app的目录，节目单，沙发管家的app列表，需要加载很久，而且经常出现加载失败的提示。关掉tunnel后，一切正常。
另外一个问题是，频繁打开视频是否对连接有影响？我为了试验各个视频的加载，打开一个剧集，如果正常播放，就快进一段时间看看速度，然后退出，试验下一个，基本上第三四个就无法打开了。即便是回到第一个刚才正常播放的视频也是无法打开。短时间请求太多有影响？

**Comment by yanggis** [comment]
沙发管家是因为这个app做的比较弱智，加载东西的时候是从远程下载zip文件来加载，会触发后台代理服务器的防御规则以为有人滥用代理服务器下载东西，会自动把链接断掉。
视频能不能打开和tunnel没有关系，tunnel仅仅是在视频没开始之前有IP的时候进行了拦截，视频一开始播放tunnel就不会拦截任何东西了。你说的这个问题应该是这个app本身就有这个问题，即便是你不用tunnel挂VPN这样返回快进快退也会卡死；还有一种情况是你的盒子内存太小，反复操作占用了太多内存，最后内存枯竭，直接卡死了。
