### ISSUE TITLE
疑問

### ISSUE THREAD

**Issue by iKeqing** [yanggis/ChinaTunnel#32]
Hi @yanggis, 

首先謝謝你的 Chinatunnel， 很棒的一個App。

今天我剛 Root 了我的Hypptv Box （人在馬來西亞）。早上芒果TV，泰捷，蜜蜂等都可以用。剛剛我再測試了一下又不行了。

1. 請問下這幾個 App 可以使用 China Tunnel 嗎？
2. 還是您建議使用什麼 App 會比較順暢？

**Comment by yanggis** [comment]
当然可以用ChinaTunnel，你说的不能看是显示区域限制，只允许中国大陆观看吗？

**Comment by iKeqing** [comment]
不管芒果還是泰捷都顯示無法連結伺服器哦

**Comment by yanggis** [comment]
怀疑你的ISP封锁了chinatunnel的通讯，你换邻居家的网络不同的ISP试试呢？

**Comment by iKeqing** [comment]
好的，我再試試看。謝謝你

**Comment by sorrych** [comment]
@yanggis好像确实出了问题
