### ISSUE TITLE
观看视频 tunnel自动关闭的问题

### ISSUE THREAD

**Issue by justinwwj** [yanggis/ChinaTunnel#33]
最近观看视频总是遇到自动关闭的问题 最为常见的是看优酷的视频 使用的是电视猫

**Comment by yanggis** [comment]
你用的是Android什么版本？

**Comment by justinwwj** [comment]
用的是小米盒子3增强版 miui 1.5.33 不清楚是基于哪个安卓版本的

**Comment by yanggis** [comment]
小米盒子的问题看看这个wiki
https://github.com/yanggis/ChinaTunnel/wiki
小米盒子内存太小，所以负优化很严重，会毫无理由的把后台进程全部杀掉，才导致chinatunnel被无故停止的。你可以试试wiki里的方法把chinatunnel设置为系统应用试试。
我本人不建议使用任何小米的设备，包括小米盒子，小米手机和小米平板电脑。
