### ISSUE TITLE
关于小米会员vip资源

### ISSUE THREAD

**Issue by crotoc** [yanggis/ChinaTunnel#4]
你好，非常感谢你开发了这个客户端，拯救了我的小米盒子。我用的小米盒子mini，看免费资源很好很流畅，于是我尝试买了个vip，想看电收费资源，结果发现悲剧了，区域限制重现了。免费资源还是没有问题，所以我感觉是VIP资源的包规则不一样。请问能帮忙调试下么，我可以帮忙抓包，非常感谢？

**Comment by yanggis** [comment]
抓包的话问题单独发邮件给我就行了，Google play商店里搜索Chinatunnel，在Chinatunnel页面最下面有我的邮箱。

**Comment by sihot** [comment]
请问 现在vip 资源可以看了吗？

**Comment by yanggis** [comment]
应该是可以看了
