### ISSUE TITLE
关于安全性上的改进建议

### ISSUE THREAD

**Issue by LBYPatrick** [yanggis/ChinaTunnel#40]
看到论坛上有人把ChinaTunnel的服务器和whitelist扒了出来，我就决定用apktool把玩一下apk安装包，结果真的...

现在的安全性问题是: 用户虽然没有root权限，但是直接把apk解开还是可能的(这个估计技术门槛不高), 而且whitelist是放在本地以sh批处理文件存在的，关键是这个whitelist貌似还会在执行``redirect.sh``的时候直接明文写到hosts里面...实在危险...

现有一个理论能实现的思路，我因为没给安卓写过东西外加不太会服务器和终端的通讯所以写不出来:

将这个whitelist直接通过**base64**编码储存在服务器上（广州腾讯云，啧啧），每次用户启动应用的时候让软件去服务器上获取这个whitelist，然后**直接放在内存里而不是在本地的临时文件里**，然后利用安卓的相关VPN API实现全局代理(shadowsocks就是靠这个永远摆脱了要root权限才能全局的痛苦)，然后再用whitelist来判断链接需不需要ChinaTunnel服务器的代理。**这样一来，开发者想抓到这个whitelist就比现在要难得多了，而且进程一结束这个whitelist就消失了**

以上。希望你能参考一下。

**Comment by yanggis** [comment]
嗯，你的建议很好，但是chinatunnel设计之初就是因为不太想搞全局VPN才设计了这个策略，我不喜欢让大家一天到晚都开着VPN，也不喜欢每次看视频都要开一次VPN才能看，这样电视盒子用户会觉得很烦的。
所以如果再回去走全局VPN的老路就没什么意义了。
whitelist知道不知道影响并不是很大，因为我们的后台服务器对所有连接进来的IP都有严格监控，发现异常流量会直接封IP.
