### ISSUE TITLE
晚上使用 China Tunnel 特別慢？

### ISSUE THREAD

**Issue by iKeqing** [yanggis/ChinaTunnel#41]
Hi Yanggis,

最近我發現晚上時使用 China Tunnel 會特別慢，不知道其他用戶是否也有相同的問題？
不管是騰訊、愛奇藝，中午看的時候都很順暢，一到晚上就特別慢？

**Comment by yanggis** [comment]
您好，您是在台湾还是香港？用的什么网络？带宽多少啊？

**Comment by iKeqing** [comment]
您好，我人在馬來西亞，用本地的Unifi，下載30mbps，上傳 10mbps

**Comment by yanggis** [comment]
我觉得最有可能还是你本地网络有问题，晚上用的人多的时候你本地网络数据拥塞，不足以提供那么快的数据传输。
你可以看看邻居家不同的ISP的网络借用一下试试。

**Comment by iKeqing** [comment]
好的，我試試看，謝謝你
另外我想請問下在China Tunnel 更改新加坡/美國的伺服器的話會不會有影響？
或者我把Router的 DNS指向 8.8.8.8 Google DNS 會不會有幫助？

**Comment by yanggis** [comment]
这对于网速来说没有任何影响。

**Comment by iKeqing** [comment]
了解， 謝謝你
