### ISSUE TITLE
芒果TV 無法播放

### ISSUE THREAD

**Issue by jj0524** [yanggis/ChinaTunnel#49]
請問有支援芒果TV版本5.5.115.200.2.SHAFA.0.0_Release嗎？如標題，出現"選擇的內容只能在中國大陸地區播放",謝謝！

**Comment by yanggis** [comment]
有没有更新whitelist再试试啊？最新版本是支持的。

**Comment by jj0524** [comment]
更新白名單後可以播放了，謝謝！
