### ISSUE TITLE
北美服务器会在2017年12月1日进行维护，届时会停机10个小时，请用北美服务器的朋友知悉。

### ISSUE THREAD

**Issue by yanggis** [yanggis/ChinaTunnel#55]
北美服务器会在2017年12月1日进行维护，届时会停机10个小时，请用北美服务器的朋友知悉。

**Comment by sorrych** [comment]
@yanggis 今天亚太服务器也无法使用吗？开启后无法观看

**Comment by sorrych** [comment]
目前是亚太服务器直接挂掉，进芒果tv打开节目后直接报错“网络链接超时，请稍后再试”，北美服务器是无法解除ip限制

**Comment by sorrych** [comment]
好像还是无法使用。辛苦开发者了@yanggis，维护完毕后能否发个公告？
