### ISSUE TITLE
小米盒子3 不兼容 Kodi ？ 

### ISSUE THREAD

**Issue by icecoldjoanne** [yanggis/ChinaTunnel#67]
我用的是海外破解版，已經加有Chinaturnnel , 我這兩天發現那個當貝軟件會自動刪走了我之前在 Kodi 加的所有插件，我再重裝，但那些 repository 是打不開, 并且那個當貝說明了不能刪，請問有沒有人有相同問題？

**Comment by yanggis** [comment]
不相关的问题不要在这提问
