### ISSUE TITLE
升级到1.91后又连接不上了

### ISSUE THREAD

**Issue by York868** [yanggis/ChinaTunnel#71]
试了北美和新加坡的服务器 看大陆视频时候又说网络设置又问题 在2个电视盒子上用的v1.91版本 出现相同的网络错误 

好像问题是从2月8日开始的。

**Comment by yanggis** [comment]
你这肯定不是最新版，从1.9版本开始就已经删除新加坡服务器了，打开软件应该显示的是台湾服务器，如果显示的是新加坡，就说明你这个APP有问题，要删除重新安装。

**Comment by York868** [comment]
谢谢 我晚上回家从新安装一下

Sent from my iPhone

On 9 Feb 2018, at 12:40 pm, X.K. YANG <notifications@github.com<mailto:notifications@github.com>> wrote:


你这肯定不是最新版，从1.9版本开始就已经删除新加坡服务器了，打开软件应该显示的是台湾服务器，如果显示的是新加坡，就说明你这个APP有问题，要删除重新安装。

**Comment by York868** [comment]
谢谢 重新安装后可以用了

Sent from my iPhone

On 9 Feb 2018, at 12:40 pm, X.K. YANG <notifications@github.com<mailto:notifications@github.com>> wrote:


你这肯定不是最新版，从1.9版本开始就已经删除新加坡服务器了，打开软件应该显示的是台湾服务器，如果显示的是新加坡，就说明你这个APP有问题，要删除重新安装。
