### ISSUE TITLE
1.9.1 開機自動啟動出問題

### ISSUE THREAD

**Issue by jj0524** [yanggis/ChinaTunnel#72]
試了1.9.1 有將開機自動啟動chinatunnel 打勾，且有將chinatunnel 轉成系統應用，重啟系統後chinatunnel 沒動作似乎hang住，開啟chinatunnel 一片灰…改回1.8版則正常沒問題

**Comment by yanggis** [comment]
安装最新版的2.0版本试试，修复了这个问题。

**Comment by jj0524** [comment]
謝謝！2.0.1版本可以了，開機自動啟動速度相較1.8版慢了約10多秒，似乎會執行2次(螢目下方出現2次"chinatunnel 已啟動")

**Comment by yanggis** [comment]
新版本故意设置了延迟20秒启动，屏幕显示信息不用理会的。。。
