### ISSUE TITLE
安裝新版本2.0.1後無法開機自動啟動

### ISSUE THREAD

**Issue by momolinkk** [yanggis/ChinaTunnel#80]
我在Android 7.0的電視盒上,新安裝2.0.1或1.9.1版本,原本可以開機自動啟動,但轉為系統應用後,變得無法自動啟動,有時會出現ChinaTunnel無回應訊息,需手動再次打開ChinaTunnel之後很慢才會啟動,如改為1.8或1.76版本就可正常轉換系統應用,開機自動啟動,請協助幫忙處理 感謝!

**Comment by yanggis** [comment]
如果可以开机启动就没必要再转为系统应用了。。。。。。。。

**Comment by momolinkk** [comment]
如沒轉為系統應用網路連線會不穩定,ChinaTunnel會開時關,不定時跑出ChinaTunnel已啟動的字幕,所以必須要轉換才行

**Comment by yanggis** [comment]
1.用link2sd修改为系统应用的时候一定要确保chinatunnel的APP和后台解锁服务是彻底关闭的，否则修改完肯定会有莫名其妙的问题；你肯定是在chinatunnel后台还运行的状态下就迫不及待的对它强行修改才造成这样的问题的；
2.改为系统应用之后，要再次打开chinatunnel，重新选中开机启动才能运行。

**Comment by momolinkk** [comment]
安裝步驟 :先移除chinatunnel2.0.1後重新開機,重新安裝chinatunnel2.0.1,安裝完後不啟動chinatunnel,先轉換為系統應用,然後重開機,打開執行chinatunnel2.0.1,重新選中開機,並按ok啟動運行,再次重開機,結果還是一樣無法開機自動啟動,無法解決問題

**Comment by yanggis** [comment]
你用的是原版的android 7.0，还是修改版的？

**Comment by yanggis** [comment]
什么牌的电视盒子，型号是什么？

**Comment by momolinkk** [comment]
我不知道是不是原版的7.0!  安博盒子 型號:I900

**Comment by yanggis** [comment]
我建议你重刷一下固件，重新root一下试试

**Comment by momolinkk** [comment]
已重刷最新固件及重新root後,結果跟之前一樣,chinatunnel2.0.1轉換為系統應用後無法自動啟動

**Comment by momolinkk** [comment]
我想可能是程式或系統相容性問題,我想說建議你是不是能把1.9.1後更新的支援android x86系統及延遲時間,改為手動開關,或許就沒一些相容性問題,開機啟動也比較快

**Comment by yanggis** [comment]
1.既然不转为系统应用的情况下可以开机启动，就证明chinatunnel没有问题；
2.我可以非常肯定的告诉你系统不是因为支援修改支援x86系统引起的；
3.具体什么问题我没有安博的电视盒子，我没法测试到底问题出在哪里，但是肯定和上面修改支援x86没有关系。

**Comment by momolinkk** [comment]
如改為1.8或1.76版本就可正常轉換系統應用,開機自動啟動,那我想應該還有改別的功能去影響到

**Comment by yanggis** [comment]
不能开机启动，你开机的时候没有报任何错误吗？你不提供任何信息给我，我怎么帮你查原因？

**Comment by yanggis** [comment]
你不能做那种简单推论1.8运行，2.0.1不能运行就认为是chinatunnel的问题，chinatunnel在这么多台机器上运行都没问题，就你的机器不行，是不是也可以推论你的盒子系统有问题呢？
你需要做的是提供信息帮我查明原因在哪，没有任何线索我不会去瞎猜修改任何代码的

**Comment by momolinkk** [comment]
開機完全不會顯示任何錯誤和啟動訊息,當你手動開啟chinatunnel,才會出現ChinaTunnel無回應訊息,按下等待,畫面hang住很慢等一會,才會顯示chinatunnel已啟動

**Comment by momolinkk** [comment]
問題跟這個有點像hang住  https://github.com/yanggis/ChinaTunnel/issues/72

**Comment by momolinkk** [comment]
所以前面我才說想可能是程式或系統相容性問題

**Comment by kevintsai1202** [comment]
我在安博上也有遇到類似的問題，有的機器能開機自啟有的不行
目前安博應該都是利用magisk manager來root的，不知道有沒有關係

**Comment by yanggis** [comment]
最大的可能还是安博盒子系统有问题，我手上没有安博的盒子没法测试问题出在什么地方，

**Comment by kevintsai1202** [comment]
我也覺得，有的可以有的不行，感覺是系統問題，比較有可能是延遲20秒的問題
手動切換都還能正常使用

另外請問一下上面提到切換成系統應用，請問要怎麼做？

**Comment by yanggis** [comment]
用Link2SD就可以转系统应用了。
