### ISSUE TITLE
为什么安装了最新版本，白名单更新不断失败？

### ISSUE THREAD

**Issue by byekitty254** [yanggis/ChinaTunnel#81]
电脑小白求救！

**Comment by byekitty254** [comment]
您好，近几天奇异果，芒果都现实网络不通，请检测网络，于是联系https://m.intl.taobao.com/detail/detail.html?id=538773510524
这款的客服，他们发来1，91版本，安装后，反复更新白名单无果，他们说需要再卸载再安装，我照做，依旧是“更新失败，请10分钟后再试！” 连续两天更新，都是一样结果。然后，google查到您这里，又下载了最新版本，卸载，安装，更新还是失败。我试着勾选了三台服务器，依旧不能更新。新年快到了，先祝您新年快乐！谢谢您的回复和帮助！

**Comment by yanggis** [comment]
你家路由器有问题，把你的电视盒子的无线网Wifi的dns改成8.8.8.8，再更新一下应该就可以了

**Comment by byekitty254** [comment]
非常感谢！现在一切如常！再次祝您新年快乐，全家幸福安康！
