### ISSUE TITLE
Taiwan Server not stable

### ISSUE THREAD

**Issue by fish7yu** [yanggis/ChinaTunnel#85]
I found that the connection and speed to the Taiwan Server starting this morning has been very unstable, I have changed the connection to Singapore Server and it is now running smoothly.

**Comment by yanggis** [comment]
This depends where you are...

**Comment by yanggis** [comment]
May I know your location, which country?

**Comment by fish7yu** [comment]
I am in Taiwan, Hsinchu.

**Comment by yanggis** [comment]
Noted, please check if the Taiwan server is recovered?

**Comment by fish7yu** [comment]
The Taiwan connection does appeared to have improved, but it is peak time right now, the speed is quite limited, so I will double check during off-peak time then let you know, thanks!

**Comment by yanggis** [comment]
Thanks

**Comment by fish7yu** [comment]
Taiwan Server connection is quite stable now, although the speed is a little bit dynamic, but overall running smoothly, thanks!

**Comment by yanggis** [comment]
Hi, thanks for the kind response.
