### ISSUE TITLE
網易雲音樂異常

### ISSUE THREAD

**Issue by TreeHD** [yanggis/ChinaTunnel#87]
B站正常
網易音樂重複出現 無法獲取播放地址
https://imgur.com/a/KVYOC

希望能解決～

**Comment by TreeHD** [comment]
附註 qq音樂也是可以使用的
只有網易雲音樂無法使用…

**Comment by yanggis** [comment]
谢谢反馈，这个我这两天看看

**Comment by yanggis** [comment]
您好，麻烦看看现在网易云音乐恢复了吗？

**Comment by TreeHD** [comment]
沒有
還是無法取得播放地址
台灣伺服器

**Comment by yanggis** [comment]
嗯，我再看看。

**Comment by yanggis** [comment]
现在再看看呢？

**Comment by TreeHD** [comment]
剛剛更新過白名單
台灣，新加坡伺服器 都不行

2018年3月18日 上午11:26，"X.K. YANG" <notifications@github.com>寫道：

**Comment by yanggis** [comment]
现在提示什么错误呢？你用的chinatunnel什么版本？

**Comment by TreeHD** [comment]
2.0.1
無法取得播放地址
B站依然正常

**Comment by yanggis** [comment]
怪了，我测了很多次，都没有问题啊。你把网易云音乐删除重装一下试试。

**Comment by TreeHD** [comment]
我升級到5.0版本就可以了
感謝

2018年3月19日 上午3:01，"X.K. YANG" <notifications@github.com>寫道：
