### ISSUE TITLE
北美服务器出错，新加坡/台湾服务器网速很慢

### ISSUE THREAD

**Issue by rainyg** [yanggis/ChinaTunnel#93]
今天（坐标北美）连接北美服务器时app（电视猫，腾讯）都显示地点在美国无法播放。使用新加坡台湾服务器时，播放速度很慢

**Comment by sorrych** [comment]
![20180520100917](https://user-images.githubusercontent.com/24655869/40274931-e944f54e-5c15-11e8-8e8d-fc80b880c351.jpg)
同样的问题

**Comment by sorrych** [comment]
@yanggis

**Comment by sorrych** [comment]
@yanggis 已经ok，感谢！
