### ISSUE TITLE
2.0.3 小米盒子 云试听极光 因版权限制您所在地区暂无法播放，您的位置是%1$s，如有誤判請反饋 50101，1300080

### ISSUE THREAD

**Issue by tonylmd** [yanggis/ChinaTunnel#95]
白名單可以刷新，台灣新加坡北美都是一樣的報錯。試過清除緩存，重裝雲視聽極光。 因版权限制您所在地区暂无法播放，您的位置是%1$s，如有誤判請反饋 50101，1300080。

**Comment by yanggis** [comment]
谢谢反馈，我检查一下什么情况。

**Comment by yanggis** [comment]
@tonylmd 您好，您是在哪个国家？IP的前两位是多少呢？我检查一下服务器。

**Comment by yanggis** [comment]
好的，谢谢，麻烦现在再试一下可以解锁吗？我刚才调整了一下服务器。

**Comment by tonylmd** [comment]
今晚可以试 感谢！

**Comment by yanggis** [comment]
好的，github wiki上有我的wechat账号，不可以用可以wechat联系我，可以给我拍照检查是什么问题。
