### ISSUE TITLE
海美迪H7二代 2.03，2.04闪退，2.02正常

### ISSUE THREAD

**Issue by phillipouyang** [yanggis/ChinaTunnel#96]
如题，2.03，2.04更新白名单正常，但按打开，不出现"运行成功，按OK键返回主界面...", 直接闪退，重装2.02后恢复正常，有空查一下，非常感谢！

**Comment by yanggis** [comment]
好的，谢谢反馈，我检查一下。

**Comment by yanggis** [comment]
另外，您的盒子android是什么系统版本呢？

**Comment by phillipouyang** [comment]
4.4.2，谢谢！

**Comment by yanggis** [comment]
@phillipouyang 
请下载这个2.0.4测试版，看看问题是不是能解决？
https://github.com/yanggis/ChinaTunnel/blob/master/ChinaTunnel.2.0.4.apk

**Comment by phillipouyang** [comment]
已删除2.02，安装2.04测试版，现象与之前一样，谢谢！

**Comment by yanggis** [comment]
谢谢反馈，麻烦安装一下这个APP，然后看一下显示的system信息：
比如 OS，API leve ,Kernel Arch， 
https://play.google.com/store/apps/details?id=io.uax.phoneinfo

**Comment by yanggis** [comment]
或者安装这个
https://play.google.com/store/apps/details?id=com.anu.main.myandroid
看里面的CPU信息。

**Comment by phillipouyang** [comment]
结果如下，谢谢!

[devinfo1.pdf](https://github.com/yanggis/ChinaTunnel/files/2087201/devinfo1.pdf)
[devinfo2.pdf](https://github.com/yanggis/ChinaTunnel/files/2087202/devinfo2.pdf)

**Comment by yanggis** [comment]
麻烦再装一下这个版本，看看是否解决问题
https://github.com/yanggis/ChinaTunnel/blob/master/ChinaTunnel.2.0.4.apk

**Comment by phillipouyang** [comment]
这个版本工作正常，太谢谢了！！！

**Comment by yanggis** [comment]
@phillipouyang  您好，能再测试一下我新优化的代码，看看还有没有崩溃的问题，2.1版本：

https://github.com/yanggis/ChinaTunnel/blob/master/ChinaTunnel.2.1.apk

**Comment by phillipouyang** [comment]
此版本正常, 谢谢!
